var items = [
	{
		id: 1,
		name: "@WhiskyVegas",
		type: "Bourbon",
		barrel: "OLS-B-1",
		age: "6yrs 1mo",
		proof: "119.34",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 2,
		name: "Alec Bradley",
		type: "Bourbon",
		barrel: "RIO-289",
		age: "6yrs 4mos",
		proof: "116.62",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 3,
		name: "Allocated Liquor",
		type: "Bourbon",
		barrel: "I21-06",
		age: "4yrs 4mos",
		proof: "116.6",
		finish: "None",
		mashbill: "",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.95",
		state: "CA",
		retail: "Top Bourbon",
		image: "i21-06.jpg"
	},

	{
		id: 4,
		name: "Bar Keeper",
		type: "Bourbon",
		barrel: "IRT-42-A",
		age: "5yrs",
		proof: "120.76",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 5,
		name: "Barrels & Brews",
		type: "Bourbon",
		barrel: "IRT-06",
		age: "5yrs 6mos",
		proof: "117.98",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 6,
		name: "Big Corks Germantown",
		type: "Bourbon",
		barrel: "IRT-26",
		age: "5yrs 6mos",
		proof: "117.42",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Corks Wine & Spirits",
		image: ""
	},

	{
		id: 7,
		name: "Bourbon Buddy",
		type: "Bourbon",
		barrel: "RIO-248",
		age: "6yrs",
		proof: "113.7",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 8,
		name: "Bourbon Enthusiast",
		type: "Bourbon",
		barrel: "RIO-223",
		age: "5yrs 9mos",
		proof: "115.8",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "Royal Batch",
		image: "rio-223.jpg"
	},

	{
		id: 9,
		name: "Bourbon Junkies",
		type: "Bourbon",
		barrel: "CC-2",
		age: "6yrs 2mos",
		proof: "117.4",
		finish: "Cognac",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 10,
		name: "Bourbon Junkies",
		type: "Bourbon",
		barrel: "RIO-209",
		age: "6yrs 1mo",
		proof: "117.86",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 11,
		name: "Bourbons Bistro",
		type: "Bourbon",
		barrel: "IRT-55",
		age: "5yrs 4mos",
		proof: "122.64",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 12,
		name: "Burlington Wine & Spirits",
		type: "Bourbon",
		barrel: "RIO-227",
		age: "6yrs 7mos",
		proof: "115.58",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "12/22",
		price: "$79.99",
		state: "MA",
		retail: "Burlington Wine & Spirits",
		image: ""
	},

	{
		id: 13,
		name: "Buster's Liquor & Wine",
		type: "Bourbon",
		barrel: "IRT-15",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$71.99",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: ""
	},

	{
		id: 14,
		name: "Buster's Liquor & Wine",
		type: "Bourbon",
		barrel: "RIO-228",
		age: "6yrs 6mos",
		proof: "114.1",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$81.99",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: ""
	},

	{
		id: 15,
		name: "Casa Fuente",
		type: "Bourbon",
		barrel: "OLS-B-2",
		age: "6yrs 5mos",
		proof: "110.78",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 16,
		name: "Cask",
		type: "Bourbon",
		barrel: "IRT-33",
		age: "5yrs 11mos",
		proof: "117.7",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 17,
		name: "Chasing Bourbon",
		type: "Bourbon",
		barrel: "RIO-287",
		age: "6yrs 6mos",
		proof: "115.64",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 18,
		name: "Chestnut Club",
		type: "Bourbon",
		barrel: "IRT-44",
		age: "5yrs",
		proof: "121.84",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "12/13/16",
		bottled: "11/12/21",
		price: "",
		state: "CA",
		retail: "",
		image: "irt-44.jpg"
	},

	{
		id: 19,
		name: "Chinglish",
		type: "Bourbon",
		barrel: "RIO-296",
		age: "5yrs 7mos",
		proof: "93",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 20,
		name: "Chip's Liquor",
		type: "Bourbon",
		barrel: "RIO-222-C",
		age: "6yrs 1mo",
		proof: "115.6",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$74.99",
		state: "CA",
		retail: "Chip's Liquor",
		image: "rio-222c.jpg"
	},

	{
		id: 21,
		name: "Corona Cigars",
		type: "Bourbon",
		barrel: "RIO-224",
		age: "6yrs 4mos",
		proof: "116.26",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "FL",
		retail: "",
		image: ""
	},

	{
		id: 22,
		name: "Cosmopolitan",
		type: "Bourbon",
		barrel: "MAD-B-05",
		age: "5yrs 5mos",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "4/2022",
		price: "",
		state: "NV",
		retail: "NFS",
		image: ""
	},

	{
		id: 23,
		name: "Cosmopolitan",
		type: "Bourbon",
		barrel: "RIO-269",
		age: "6yrs 7mos",
		proof: "112.64",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "NFS",
		image: ""
	},

	{
		id: 24,
		name: "Curiada",
		type: "Bourbon",
		barrel: "IRT-02",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CT",
		retail: "Curiada",
		image: ""
	},

	{
		id: 25,
		name: "Del Mesa Liquor",
		type: "Bourbon",
		barrel: "RIO-222-A",
		age: "6yrs 1mo",
		proof: "115.6",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$79.99",
		state: "CA",
		retail: "Del Mesa Liquor",
		image: "rio-222a.jpg"
	},

	{
		id: 26,
		name: "Dion's",
		type: "Bourbon",
		barrel: "RIO-238",
		age: "6yrs 7mos",
		proof: "113.42",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "MA",
		retail: "Dion's ",
		image: ""
	},

	{
		id: 27,
		name: "Dion's",
		type: "Bourbon",
		barrel: "RIO-240",
		age: "6yrs 7mos",
		proof: "114.14",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "MA",
		retail: "Dion's",
		image: ""
	},

	{
		id: 28,
		name: "Eataly at Park MGM",
		type: "Bourbon",
		barrel: "RIO-242",
		age: "5yrs 10mos",
		proof: "94",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$120.00",
		state: "NV",
		retail: "Eataly",
		image: ""
	},

	{
		id: 29,
		name: "El Cerrito Liquor",
		type: "Bourbon",
		barrel: "IRT-25",
		age: "5yrs 6mos",
		proof: "117.22",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "5/22",
		price: "$75.00",
		state: "CA",
		retail: "El Cerrito",
		image: ""
	},

	{
		id: 30,
		name: "Elixir",
		type: "Bourbon",
		barrel: "IRT-51",
		age: "5yrs 10mos",
		proof: "120.78",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 31,
		name: "Ettan",
		type: "Bourbon",
		barrel: "RIO-205",
		age: "5yrs 9mos",
		proof: "90",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 32,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "RIO-243",
		age: "6yrs 2mos",
		proof: "104.58",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 33,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "RIO-255",
		age: "6yrs 2mos",
		proof: "118.02",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 34,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-03",
		age: "4yrs 7mos",
		proof: "114.94",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 35,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-07",
		age: "",
		proof: "116.44",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 36,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-09",
		age: "",
		proof: "116.2",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 37,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-11",
		age: "",
		proof: "118.24",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 38,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-14",
		age: "4yrs 9mos",
		proof: "116.86",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 39,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-15",
		age: "",
		proof: "117.86",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 40,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-20",
		age: "4yrs 9mos",
		proof: "115.24",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
	},

	{
		id: 41,
		name: "Fernside",
		type: "Bourbon",
		barrel: "RIO-239",
		age: "5yrs 10mos",
		proof: "113.92",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 42,
		name: "Founder's Choice",
		type: "Bourbon",
		barrel: "IRT-07",
		age: "5yrs 7mos",
		proof: "118.48",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/2016",
		bottled: "1/2022",
		price: "$69.99",
		state: "NY",
		retail: "Mash & Grape",
		image: "irt-07.jpg"
	},

	{
		id: 43,
		name: "Founder's Choice",
		type: "Bourbon",
		barrel: "IRT-20",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "NY",
		retail: "Mash & Grape",
		image: "irt-20.jpg"
	},

	{
		id: 44,
		name: "Founder's Choice",
		type: "Bourbon",
		barrel: "RIO-273",
		age: "5yrs 8mos",
		proof: "116.36",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/2016",
		bottled: "1/2022",
		price: "",
		state: "NY",
		retail: "",
		image: "rio-273.jpg"
	},

	{
		id: 45,
		name: "George Awad and the Neat Freaks",
		type: "Bourbon",
		barrel: "BAL-B-02",
		age: "5yrs 2mos",
		proof: "114.06",
		finish: "Balsamo",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "FL",
		retail: "Sunshine Liquor",
		image: ""
	},

	{
		id: 46,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		barrel: "RIO-213",
		age: "6yrs",
		proof: "116.96",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "rio-213.jpg"
	},

	{
		id: 47,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		barrel: "RIO-214",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 48,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		barrel: "RIO-260",
		age: "6yrs 6mos",
		proof: "112.24",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 49,
		name: "Good Lion",
		type: "Bourbon",
		barrel: "IRT-05",
		age: "5yrs 3mos",
		proof: "101",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 50,
		name: "Gordon's",
		type: "Bourbon",
		barrel: "RIO-270",
		age: "6yrs 7mos",
		proof: "117.14",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "12/22",
		price: "$74.99",
		state: "MA",
		retail: "Gordon's Wine",
		image: "rio-270.jpg"
	},

	{
		id: 51,
		name: "Hatchet Hall",
		type: "Bourbon",
		barrel: "IRT-46",
		age: "",
		proof: "107.2",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 52,
		name: "Helix Liquor",
		type: "Bourbon",
		barrel: "RIO-222B",
		age: "6yrs 1mos",
		proof: "115.6",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$79.99",
		state: "CA",
		retail: "Bottle Broz",
		image: "rio-222b.jpg"
	},

	{
		id: 53,
		name: "Heritage Selections",
		type: "Bourbon",
		barrel: "RIO-229",
		age: "5yrs 8mos",
		proof: "114.92",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/2016",
		bottled: "1/2022",
		price: "",
		state: "KY",
		retail: "",
		image: "rio-229.jpg"
	},

	{
		id: 54,
		name: "Heritage Selections",
		type: "Bourbon",
		barrel: "I21-08",
		age: "4yrs 5mos",
		proof: "116.3",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 55,
		name: "Hi-Time Wine Cellars",
		type: "Bourbon",
		barrel: "RIO-295",
		age: "5yrs 9mos",
		proof: "117.12",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Hi-Time Wine Cellars",
		image: ""
	},

	{
		id: 56,
		name: "Hotel Covington",
		type: "Bourbon",
		barrel: "RIO-265",
		age: "5yrs 8mos",
		proof: "117.96",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 57,
		name: "Jarred Dooley",
		type: "Bourbon",
		barrel: "IRT-40",
		age: "5yrs",
		proof: "119.22",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/12/16",
		bottled: "11/12/21",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 58,
		name: "Joe C",
		type: "Bourbon",
		barrel: "IRT-27",
		age: "5yrs",
		proof: "116.66",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16/16",
		bottled: "11/28/21",
		price: "",
		state: "CA",
		retail: "Everson Royce",
		image: "irt-27.jpg"
	},

	{
		id: 59,
		name: "Joe C",
		type: "Bourbon",
		barrel: "JR-1 / KHT-02",
		age: "4yrs 11mos",
		proof: "118.48",
		finish: "Jamaican Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "4/22",
		price: "$103.00",
		state: "CA",
		retail: "Everson Royce",
		image: ""
	},

	{
		id: 60,
		name: "Joe C with No Us Without You",
		type: "Bourbon",
		barrel: "RIO-213-A",
		age: "6yrs",
		proof: "113.72",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$92.00",
		state: "CA",
		retail: "Everson Royce",
		image: ""
	},

	{
		id: 61,
		name: "Justin's House of Bourbon",
		type: "Bourbon",
		barrel: "RIO-256",
		age: "6yrs",
		proof: "118.34",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Justin's House of Bourbon",
		image: ""
	},

	{
		id: 62,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		barrel: "IRT-21",
		age: "5yrs",
		proof: "119.68",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "irt-21.jpg"
	},

	{
		id: 63,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		barrel: "IRT-24",
		age: "5yrs",
		proof: "119.68",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "irt-24.jpg"
	},

	{
		id: 64,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		barrel: "RIO-234",
		age: "6yrs",
		proof: "115.44",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "rio-234.jpg"
	},

	{
		id: 65,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		barrel: "RIO-254",
		age: "6yrs",
		proof: "112.86",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "rio-254.jpg"
	},

	{
		id: 66,
		name: "Khoury's",
		type: "Bourbon",
		barrel: "WP-B-05",
		age: "6yrs 6mos",
		proof: "104.42",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "11/22",
		price: "",
		state: "NV",
		retail: "Khoury's",
		image: ""
	},

	{
		id: 67,
		name: "Khoury's Fine Wine",
		type: "Bourbon",
		barrel: "RIO-261",
		age: "6yrs",
		proof: "114.04",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Khoury's",
		image: ""
	},

	{
		id: 68,
		name: "Lake District Wine & Liquor",
		type: "Bourbon",
		barrel: "IRT-10",
		age: "5yrs 6mos",
		proof: "120.16",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 69,
		name: "Laundry Room",
		type: "Bourbon",
		barrel: "I21-16",
		age: "4yrs 6mos",
		proof: "96",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "NFS",
		image: ""
	},

	{
		id: 70,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		barrel: "IRT-18",
		age: "5yrs 4mos",
		proof: "118.8",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: "irt-18.jpg"
	},

	{
		id: 71,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		barrel: "OLS-B-05",
		age: "5yrs 11mos",
		proof: "112.74",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: ""
	},

	{
		id: 72,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		barrel: "RIO-232",
		age: "6yrs 5mos",
		proof: "112.84",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: ""
	},

	{
		id: 73,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		barrel: "RIO-244",
		age: "5yrs 10mos",
		proof: "114.72",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: ""
	},

	{
		id: 74,
		name: "Life of Luxe",
		type: "Bourbon",
		barrel: "RIO-262",
		age: "6yrs",
		proof: "118.34",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 75,
		name: "Liquor Barn",
		type: "Bourbon",
		barrel: "IRT-38",
		age: "5yrs 1mo",
		proof: "118.26",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "12/16",
		bottled: "1/22",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: ""
	},

	{
		id: 76,
		name: "Liquor Barn",
		type: "Bourbon",
		barrel: "RIO-300",
		age: "5yrs 7mos",
		proof: "116.3",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: ""
	},

	{
		id: 77,
		name: "Liquor Barn",
		type: "Bourbon",
		barrel: "I21-12",
		age: "4yrs 6mos",
		proof: "116.76",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: ""
	},

	{
		id: 78,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Bourbon",
		barrel: "OLS-13-04",
		age: "6yrs 7mos",
		proof: "110.1",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "12/22",
		price: "",
		state: "MA",
		retail: "Liquor Junction",
		image: ""
	},

	{
		id: 79,
		name: "LiquorLineup.com",
		type: "Bourbon",
		barrel: "RIO-219",
		age: "5yrs 7mos",
		proof: "117.74",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "NV",
		retail: "LiquorLineup.com",
		image: ""
	},

	{
		id: 80,
		name: "Littlebear Bottleshop",
		type: "Bourbon",
		barrel: "IRT-42-B",
		age: "5yrs",
		proof: "120.76",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 81,
		name: "Littlebear Bottleshop",
		type: "Bourbon",
		barrel: "OLS-B-06",
		age: "5yrs 6mos",
		proof: "110.78",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 82,
		name: "Local Feed",
		type: "Bourbon",
		barrel: "RIO-286-B",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 83,
		name: "Lotus of Siam",
		type: "Bourbon",
		barrel: "RIO-204",
		age: "6yrs 1mo",
		proof: "95",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 84,
		name: "Lotus of Siam",
		type: "Bourbon",
		barrel: "RIO-226",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 85,
		name: "Major League Bourbon Clubhouse",
		type: "Bourbon",
		barrel: "",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 86,
		name: "Majority Rule",
		type: "Bourbon",
		barrel: "IRT-53",
		age: "5yrs 7mos",
		proof: "111.14",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 87,
		name: "Mash & Journey Whiskey Club",
		type: "Bourbon",
		barrel: "RIO-290",
		age: "6yrs",
		proof: "113.54",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$82.99",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 88,
		name: "MGM Resorts",
		type: "Bourbon",
		barrel: "RIO-251",
		age: "6yrs 5mos",
		proof: "95",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 89,
		name: "Michael Mina",
		type: "Bourbon",
		barrel: "RIO-201",
		age: "5yrs 9mos",
		proof: "115.84",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 90,
		name: "Michael Mina",
		type: "Bourbon",
		barrel: "RIO-220",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 91,
		name: "Michael Mina",
		type: "Bourbon",
		barrel: "RIO-283",
		age: "6yrs",
		proof: "104.24",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 92,
		name: "Michael P. Trow & Gia St. George Terry",
		type: "Bourbon",
		barrel: "RIO-211",
		age: "6yrs 5mos",
		proof: "95.4",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/2016",
		bottled: "10/2022",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 93,
		name: "Mission Wine & Spirits",
		type: "Bourbon",
		barrel: "IRT-30",
		age: "5yrs",
		proof: "119.58",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16/2016",
		bottled: "11/18/2021",
		price: "",
		state: "CA",
		retail: "",
		image: "irt-30.jpg"
	},

	{
		id: 94,
		name: "Mission Wine & Spirits",
		type: "Bourbon",
		barrel: "IRT-59",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "irt-59.jpg"
	},

	{
		id: 95,
		name: "Mister O's",
		type: "Bourbon",
		barrel: "IRT-19-B",
		age: "5yrs 8mos",
		proof: "118.28",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 96,
		name: "Mixing Glass",
		type: "Bourbon",
		barrel: "IRT-12-B",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 97,
		name: "Mixing Glass",
		type: "Bourbon",
		barrel: "I21-13-A",
		age: "4yrs 4mos",
		proof: "117.6",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "7/13/2017",
		bottled: "11/18/2021",
		price: "",
		state: "CA",
		retail: "",
		image: "i21-13a.jpg"
	},

	{
		id: 98,
		name: "Moye O'Brien Bourbon Crew",
		type: "Bourbon",
		barrel: "RIO-218",
		age: "6yrs 4mos",
		proof: "114.78",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 99,
		name: "Mr Whiskers",
		type: "Bourbon",
		barrel: "IRT-03",
		age: "5yrs 11mos",
		proof: "119.74",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Mr Whiskers Wines & Liquors",
		image: ""
	},

	{
		id: 100,
		name: "Mr Whiskers",
		type: "Bourbon",
		barrel: "RIO-288",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Mr Whiskers Wines & Liquors",
		image: ""
	},

	{
		id: 101,
		name: "Mythical",
		type: "Bourbon",
		barrel: "MAD-4",
		age: "5yrs",
		proof: "117.23",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 102,
		name: "Nashville Daily",
		type: "Bourbon",
		barrel: "IRT-41",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 103,
		name: "OBC Kitchen",
		type: "Bourbon",
		barrel: "121-13-B",
		age: "4yrs 4mos",
		proof: "117.6",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "7/17",
		bottled: "11/21",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 104,
		name: "Old Man Bar",
		type: "Bourbon",
		barrel: "IRT-18",
		age: "4yrs 4mos",
		proof: "116.14",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "7/13/2017",
		bottled: "11/12/2021",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 105,
		name: "Old Man Bar",
		type: "Bourbon",
		barrel: "IRT-46",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 106,
		name: "Old Man Bar",
		type: "Bourbon",
		barrel: "I21-18",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 107,
		name: "On The Thirty",
		type: "Bourbon",
		barrel: "IRT-19-A",
		age: "5yrs 2mos",
		proof: "118.28",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 108,
		name: "Obliteration",
		type: "Bourbon",
		barrel: "",
		age: "14yrs",
		proof: "143.8",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$599.99",
		state: "DC",
		retail: "Seelbach's",
		image: "obliteration.jpg"
	},

	{
		id: 109,
		name: "Pacifica Hotels",
		type: "Bourbon",
		barrel: "I21-01",
		age: "",
		proof: "90",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 110,
		name: "Party Source",
		type: "Bourbon",
		barrel: "RIO-259",
		age: "5yrs 9mos",
		proof: "117.12",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 111,
		name: "Prime Barrel",
		type: "Bourbon",
		barrel: "RIO-235",
		age: "6yrs 6mos",
		proof: "113.18",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "rio-235.jpg"
	},

	{
		id: 112,
		name: "Raised by Wolves",
		type: "Bourbon",
		barrel: "IRT-34",
		age: "5yrs 1 mo",
		proof: "116.26",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "12/2016",
		bottled: "1/2022",
		price: "",
		state: "CA",
		retail: "Bar Cart",
		image: "irt-34.jpg"
	},

	{
		id: 113,
		name: "Rapid Liquors",
		type: "Bourbon",
		barrel: "RIO-236",
		age: "6yrs 7mos",
		proof: "114.12",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$68.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: ""
	},

	{
		id: 114,
		name: "Rare Bird 101",
		type: "Bourbon",
		barrel: "RIO-241",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 115,
		name: "Raymond 1886",
		type: "Bourbon",
		barrel: "RIO-297",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 116,
		name: "Red Dog",
		type: "Bourbon",
		barrel: "IRT-17",
		age: "5yrs 6mos",
		proof: "117.66",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "TN",
		retail: "Red Dog",
		image: ""
	},

	{
		id: 117,
		name: "Red Dog",
		type: "Bourbon",
		barrel: "JR-B-02",
		age: "4yrs 10mos",
		proof: "118.48",
		finish: "Jamaican Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "TN",
		retail: "Red Dog",
		image: ""
	},

	{
		id: 118,
		name: "Red Dog",
		type: "Bourbon",
		barrel: "WP-B-04",
		age: "5yrs",
		proof: "110.82",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$109.99",
		state: "TN",
		retail: "Red Dog",
		image: ""
	},

	{
		id: 119,
		name: "Redbird",
		type: "Bourbon",
		barrel: "RIO-278",
		age: "6yrs",
		proof: "114.8",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 120,
		name: "Republique",
		type: "Bourbon",
		barrel: "RIO-264",
		age: "5yrs 3mos",
		proof: "113.68",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "May 2016",
		bottled: "Jan 2022",
		price: "",
		state: "CA",
		retail: "Republique",
		image: ""
	},

	{
		id: 121,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		barrel: "IRT-25-2",
		age: "5yrs 4mos",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$114.99",
		state: "KY",
		retail: "",
		image: "irt-25.jpg"
	},

	{
		id: 122,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		barrel: "IRT-36A",
		age: "6yrs",
		proof: "115.12",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 123,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		barrel: "RIO-286-A",
		age: "6yrs",
		proof: "115.12",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 124,
		name: "Sahara Las Vegas",
		type: "Bourbon",
		barrel: "IRT-23",
		age: "5yrs",
		proof: "89.5",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 125,
		name: "Sahara Las Vegas",
		type: "Bourbon",
		barrel: "MAD-1",
		age: "5yrs",
		proof: "104",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 126,
		name: "Sand Dollar",
		type: "Bourbon",
		barrel: "RIO-298",
		age: "6yrs 5mos",
		proof: "113.02",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 127,
		name: "Santee Market & Liquor / BPWC",
		type: "Bourbon",
		barrel: "IRT-13",
		age: "6yrs",
		proof: "117.72",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "11/22",
		price: "$79.99",
		state: "CA",
		retail: "F&D Wine and Spirits",
		image: ""
	},

	{
		id: 128,
		name: "Scopa Italian Roots",
		type: "Bourbon",
		barrel: "IRT-22",
		age: "5yrs",
		proof: "119.18",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 129,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "IRT-35",
		age: "5yrs",
		proof: "117.32",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: "irt-35.jpg"
	},

	{
		id: 130,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "IRT-60",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: ""
	},

	{
		id: 131,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "MAD-B-1",
		age: "5yrs",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: "mad-b-1.jpg"
	},

	{
		id: 132,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "WP-1",
		age: "6yrs 7mos",
		proof: "113.48",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: "wp-1.jpg"
	},

	{
		id: 133,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "RIO-202",
		age: "6yrs",
		proof: "115.52",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-202.jpg"
	},

	{
		id: 134,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "RIO-252",
		age: "6yrs",
		proof: "113.62",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-252.jpg"
	},

	{
		id: 135,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "RIO-267",
		age: "6yrs",
		proof: "114.78",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-267.jpg"
	},

	{
		id: 136,
		name: "Seelbach's & Bourbon Enthusiast",
		type: "Bourbon",
		barrel: "WP-B-2",
		age: "5yrs",
		proof: "109.26",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "6/22",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: "wp-b-2.jpg"
	},

	{
		id: 137,
		name: "Sinkers Wine & Spirits",
		type: "Bourbon",
		barrel: "RIO-282",
		age: "6yrs 2mos",
		proof: "118.2",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 138,
		name: "Southern Arizona Whiskey Society",
		type: "Bourbon",
		barrel: "WP-B-03",
		age: "5yrs 6mos",
		proof: "111.1",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "AZ",
		retail: "Batch",
		image: ""
	},

	{
		id: 139,
		name: "Southern Whiskey Society",
		type: "Bourbon",
		barrel: "IRT-54",
		age: "5yrs 7mos",
		proof: "102.6",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/2016",
		bottled: "6/2022",
		price: "$69.99",
		state: "TN",
		retail: "Red Dog",
		image: "irt-54.jpg"
	},

	{
		id: 140,
		name: "Spiegelworld",
		type: "Bourbon",
		barrel: "IRT-31",
		age: "5yrs 7mos",
		proof: "119.9",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "6/22",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 141,
		name: "Spiegelworld",
		type: "Bourbon",
		barrel: "IRT-31",
		age: "5yrs 7mos",
		proof: "95",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "6/22",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 142,
		name: "Spiegelworld",
		type: "Bourbon",
		barrel: "KHT-22",
		age: "5yrs",
		proof: "59.11",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 143,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		barrel: "IRT-29",
		age: "5yrs 6mos",
		proof: "116.88",
		finish: "PX Sherry",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: "irt-29.jpg"
	},

	{
		id: 144,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		barrel: "RIO-215",
		age: "5yrs 8mos",
		proof: "112.52",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-215.jpg"
	},

	{
		id: 145,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		barrel: "RIO-221",
		age: "5yrs 8mos",
		proof: "115.52",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 146,
		name: "Thunderbolt",
		type: "Bourbon",
		barrel: "IRT-11",
		age: "5yrs",
		proof: "90",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 147,
		name: "Top's Liquor",
		type: "Bourbon",
		barrel: "MAD-B-58",
		age: "5yrs",
		proof: "112.34",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Top's Liquor",
		image: ""
	},

	{
		id: 148,
		name: "Top's Liquor",
		type: "Bourbon",
		barrel: "RIO-206",
		age: "6yrs 5mos",
		proof: "113.02",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Top's Liquor",
		image: ""
	},

	{
		id: 149,
		name: "Total Wine & More",
		type: "Bourbon",
		barrel: "FSR-B-02",
		age: "6yrs 7mos",
		proof: "110.34",
		finish: "Barbados Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 150,
		name: "Trevor's Liquors",
		type: "Bourbon",
		barrel: "RIO-212",
		age: "6yrs 1mos",
		proof: "115.52",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Trevor's Liquors",
		image: ""
	},

	{
		id: 151,
		name: "Vintage Corks",
		type: "Bourbon",
		barrel: "IRT-09",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 152,
		name: "Vintage Corks",
		type: "Bourbon",
		barrel: "IRT-28",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 153,
		name: "Vintage Corks",
		type: "Bourbon",
		barrel: "RIO-287",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 154,
		name: "Westport Whiskey & Wine",
		type: "Bourbon",
		barrel: "RIO-249",
		age: "5yrs 7mos",
		proof: "114.18",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "rio-249.jpg"
	},

	{
		id: 155,
		name: "Whiskey Locator",
		type: "Bourbon",
		barrel: "RIO-299",
		age: "6yrs",
		proof: "118.48",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: ""
	},

	{
		id: 156,
		name: "Wine Chap",
		type: "Bourbon",
		barrel: "IRT-32",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 157,
		name: "Wine Chap",
		type: "Bourbon",
		barrel: "RIO-207",
		age: "6yrs 5mos",
		proof: "114.48",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 158,
		name: "Winston House",
		type: "Bourbon",
		barrel: "IRT-37",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 159,
		name: "Winston House",
		type: "Bourbon",
		barrel: "IRT-45",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 160,
		name: "Unknown",
		type: "Bourbon",
		barrel: "",
		age: "",
		proof: "",
		finish: "Eucalipto",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 161,
		name: "Accomplice Bar",
		type: "Rye",
		barrel: "I95-07",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "95/5",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 162,
		name: "ADHD Fishing",
		type: "Rye",
		barrel: "KRY-547",
		age: "6yrs 6mos",
		proof: "121.2",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "kry-547.jpg"
	},

	{
		id: 163,
		name: "Allocated Liquor",
		type: "Rye",
		barrel: "I95-14",
		age: "5yrs",
		proof: "113.94",
		finish: "None",
		mashbill: "95/5",
		source: "MGP",
		distilled: "11/28/2016",
		bottled: "11/28/2021",
		price: "$69.95",
		state: "CA",
		retail: "Top Bourbon",
		image: "i95-14.jpg"
	},

	{
		id: 164,
		name: "Aman's",
		type: "Rye",
		barrel: "KRY-534-B",
		age: "7rys 4mos",
		proof: "122.7",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "WI",
		retail: "Aman's",
		image: "kry-534b.jpg"
	},

	{
		id: 165,
		name: "Barrels & Brews",
		type: "Rye",
		barrel: "KRY-545",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},

	{
		id: 166,
		name: "Bayway World of Liquor",
		type: "Rye",
		barrel: "AMB-R-19",
		age: "6yrs 6mos",
		proof: "112.06",
		finish: "Amburana",
		mashbill: "95/5",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "NJ",
		retail: "Bayway",
		image: ""
	},

	{
		id: 167,
		name: "Born & Raised",
		type: "Rye",
		barrel: "I95-10",
		age: "4yrs 4mos",
		proof: "113.8",
		finish: "None",
		mashbill: "",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 168,
		name: "Bourbon Outfitter",
		type: "Rye",
		barrel: "AMB-04",
		age: "5yrs 7mos",
		proof: "113.64",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Bourbon Outfitter",
		image: ""
	},

	{
		id: 169,
		name: "Bourbon Pursuit Podcast",
		type: "Rye",
		barrel: "KRY-567",
		age: "6yrs 1mos",
		proof: "121.68",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "kry-567.jpg"
	},

	{
		id: 170,
		name: "Brown Jug",
		type: "Rye",
		barrel: "AMB-03-A",
		age: "5yrs 7mos",
		proof: "115.78",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "AK",
		retail: "",
		image: ""
	},

	{
		id: 171,
		name: "Buster's Liquor & Wine",
		type: "Rye",
		barrel: "I95-17",
		age: "5yrs 6mos",
		proof: "115.06",
		finish: "None",
		mashbill: "",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: "i95-17.png"
	},

	{
		id: 172,
		name: "Buster's Liquor & Wine",
		type: "Rye",
		barrel: "KRY-542-A",
		age: "6yrs 7mos",
		proof: "121.28",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: ""
	},

	{
		id: 173,
		name: "CH Projects",
		type: "Rye",
		barrel: "I95-10",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "95/5",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 174,
		name: "Chasing Bourbon",
		type: "Rye",
		barrel: "KRY-546",
		age: "6yrs 6mos",
		proof: "120.1",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 175,
		name: "Chicagoland Whiskey",
		type: "Rye",
		barrel: "KRY-564",
		age: "6yrs 1mo",
		proof: "122.6",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 176,
		name: "Cosmopolitan",
		type: "Rye",
		barrel: "AMB-R-03-A",
		age: "6yrs",
		proof: "115.8",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "NFS",
		image: ""
	},

	{
		id: 177,
		name: "Cosmopolitan",
		type: "Rye",
		barrel: "KRY-530",
		age: "6yrs 7mos",
		proof: "122",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/2016",
		bottled: "12/2022",
		price: "",
		state: "NV",
		retail: "NFS",
		image: ""
	},

	{
		id: 178,
		name: "Dama",
		type: "Rye",
		barrel: "TNR-08",
		age: "5yrs 6mos",
		proof: "111.42",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 179,
		name: "El Cerrito",
		type: "Rye",
		barrel: "KRY-569",
		age: "6yrs 6mos",
		proof: "121.04",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "11/22",
		price: "$95.00",
		state: "CA",
		retail: "El Cerrito",
		image: "kry-569.jpg"
	},

	{
		id: 180,
		name: "Elixir",
		type: "Rye",
		barrel: "KRY-570",
		age: "7yrs 4mos",
		proof: "122.1",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/15",
		bottled: "9/22",
		price: "",
		state: "TN",
		retail: "",
		image: "kry-570.jpg"
	},

	{
		id: 181,
		name: "Eureka!",
		type: "Rye",
		barrel: "KRY-529",
		age: "6yrs 5mos",
		proof: "121.88",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 182,
		name: "Eureka!",
		type: "Rye",
		barrel: "KRY-541",
		age: "6yrs 5mos",
		proof: "121.88",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 183,
		name: "Evel Pie",
		type: "Rye",
		barrel: "RHY-7B",
		age: "4yrs 9mos",
		proof: "103",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 184,
		name: "Five / Five",
		type: "Rye",
		barrel: "AMB-04",
		age: "4yrs",
		proof: "105",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 185,
		name: "Founder's Choice",
		type: "Rye",
		barrel: "RHY-20",
		age: "4yrs 4mos",
		proof: "115.88",
		finish: "None",
		mashbill: "51/45/4",
		source: "",
		distilled: "9/17",
		bottled: "1/22",
		price: "$59.99",
		state: "NY",
		retail: "Mash & Grape",
		image: "rhy-20.jpg"
	},

	{
		id: 186,
		name: "G & R Embry",
		type: "Rye",
		barrel: "RHY-17-B",
		age: "4yrs 2mos",
		proof: "101",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NY",
		retail: "NFS",
		image: ""
	},

	{
		id: 187,
		name: "Golden Tiki",
		type: "Rye",
		barrel: "RHY-07-A",
		age: "4yrs 9mos",
		proof: "103",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 188,
		name: "Gordon's",
		type: "Rye",
		barrel: "",
		age: "",
		proof: "",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "MA",
		retail: "Gordon's Wine",
		image: ""
	},

	{
		id: 189,
		name: "Gordon's",
		type: "Rye",
		barrel: "KRY-523",
		age: "6yrs 7mos",
		proof: "88.22",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "12/22",
		price: "$94.99",
		state: "MA",
		retail: "Gordon's Wine",
		image: "kry-523.jpg"
	},

	{
		id: 190,
		name: "Heritage Selections",
		type: "Rye",
		barrel: "KRY-565",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},

	{
		id: 191,
		name: "Hi-Time Wine Cellars",
		type: "Rye",
		barrel: "TNR-02",
		age: "4yrs 3mos",
		proof: "111.46",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Hi-Time Wine Cellars",
		image: ""
	},

	{
		id: 192,
		name: "Jarred Dooley",
		type: "Rye",
		barrel: "TNR-01",
		age: "",
		proof: "110.34",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 193,
		name: "Joe C",
		type: "Rye",
		barrel: "I95-15",
		age: "5yrs",
		proof: "113.08",
		finish: "None",
		mashbill: "95/5",
		source: "MGP",
		distilled: "11/28/2016",
		bottled: "12/06/2021",
		price: "",
		state: "CA",
		retail: "Everson Royce",
		image: "i95-15.jpg"
	},

	{
		id: 194,
		name: "K&L Wine Merchants",
		type: "Rye",
		barrel: "TNR-04",
		age: "5yrs 6mos",
		proof: "110.62",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "1/12/2016",
		bottled: "10/15/2021",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "tnr-04.jpg"
	},

	{
		id: 195,
		name: "K&L Wine Merchants",
		type: "Rye",
		barrel: "TNR-07",
		age: "5yrs 6mos",
		proof: "111",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "tnr-07.jpg"
	},

	{
		id: 196,
		name: "Keg n Bottle & Rare Bird 101",
		type: "Rye",
		barrel: "101-95",
		age: "5yrs 9mos",
		proof: "113.16",
		finish: "PX Sherry",
		mashbill: "95/5",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Keg n Bottle",
		image: ""
	},

	{
		id: 197,
		name: "Khoury's Fine Wine",
		type: "Rye",
		barrel: "TNR-10",
		age: "5yrs 6mos",
		proof: "109.42",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Khoury's",
		image: ""
	},

	{
		id: 198,
		name: "Last Chance Liquors",
		type: "Rye",
		barrel: "KRY-573",
		age: "6yrs 7mos",
		proof: "122.82",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "12/22",
		price: "",
		state: "TN",
		retail: "Last Chance Liquors",
		image: ""
	},

	{
		id: 199,
		name: "Lee's Discount Liquor",
		type: "Rye",
		barrel: "EUC-R-01",
		age: "5yrs",
		proof: "115.1",
		finish: "Eucalipto",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "June 2022",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: ""
	},

	{
		id: 200,
		name: "Liquor Depot",
		type: "Rye",
		barrel: "KRY-568",
		age: "6yrs 7mos",
		proof: "121.16",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "May 2016",
		bottled: "Dec 2022",
		price: "",
		state: "OR",
		retail: "Liquor Depot",
		image: ""
	},

	{
		id: 201,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Rye",
		barrel: "KRY-549-B",
		age: "6yrs 7mos",
		proof: "121.18",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "MA",
		retail: "Liquor Junction",
		image: ""
	},

	{
		id: 202,
		name: "LiquorLineup.com",
		type: "Rye",
		barrel: "KRY-564",
		age: "6yrs 2mos",
		proof: "122.5",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "7/22",
		price: "",
		state: "NV",
		retail: "LiquorLineup.com",
		image: ""
	},

	{
		id: 203,
		name: "Littlebear Bottleshop",
		type: "Rye",
		barrel: "AMB-R-02-A",
		age: "6yrs",
		proof: "115.8",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 204,
		name: "Loch & K(e)y",
		type: "Rye",
		barrel: "KRY-526-A",
		age: "6yrs 7mos",
		proof: "121.04",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "MA",
		retail: "",
		image: ""
	},

	{
		id: 205,
		name: "Mina",
		type: "Rye",
		barrel: "TNR-05",
		age: "5yrs 5mos",
		proof: "112.24",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 206,
		name: "Mythical",
		type: "Rye",
		barrel: "KRY-534-A",
		age: "7yrs 4mos",
		proof: "122.7",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 207,
		name: "Omni",
		type: "Rye",
		barrel: "",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 208,
		name: "Pacific Cocktail Haven",
		type: "Rye",
		barrel: "KRY-548",
		age: "5yrs 10mos",
		proof: "122.1",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown ",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 209,
		name: "Pacifica Hotels",
		type: "Rye",
		barrel: "TNR-06-B",
		age: "4yrs 6mos",
		proof: "112.4",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "7/17",
		bottled: "11/21",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 210,
		name: "Playa Provisions",
		type: "Rye",
		barrel: "TNR-06A",
		age: "6yrs",
		proof: "112.4",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},

	{
		id: 211,
		name: "Prime Barrel",
		type: "Rye",
		barrel: "KRY-521",
		age: "6yrs 6mos",
		proof: "119.76",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "kry-521.jpg"
	},

	{
		id: 212,
		name: "Rapid Liquors",
		type: "Rye",
		barrel: "KRY-557-A",
		age: "6yrs 7mos",
		proof: "122.06",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "MA",
		retail: "",
		image: ""
	},

	{
		id: 213,
		name: "Rare Bird 101",
		type: "Rye",
		barrel: "KRY-544",
		age: "6yrs 4mos",
		proof: "120.3",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "kry-544.jpg"
	},

	{
		id: 214,
		name: "Red Dog",
		type: "Rye",
		barrel: "KRY-561",
		age: "5yrs 11mos",
		proof: "117.98",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "TN",
		retail: "Red Dog",
		image: ""
	},

	{
		id: 215,
		name: "Republique",
		type: "Rye",
		barrel: "KRY-524",
		age: "6yrs 5mos",
		proof: "121.86",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "May 2016",
		bottled: "Oct 2022",
		price: "",
		state: "CA",
		retail: "Republique",
		image: ""
	},

	{
		id: 216,
		name: "ReserveBar TopFlight Series",
		type: "Rye",
		barrel: "AMB-R-06",
		age: "5yrs 11mos",
		proof: "115.28",
		finish: "Amburana",
		mashbill: "51/45/4",
		source: "Bardstown",
		distilled: "12/16",
		bottled: "11/22",
		price: "$92.99",
		state: "CA",
		retail: "ReserveBar",
		image: "amb-r-06.png"
	},

	{
		id: 217,
		name: "ReserveBar TopFlight Series",
		type: "Rye",
		barrel: "JAQ-R-01",
		age: "4yrs 6mos",
		proof: "113.3",
		finish: "Jaqueira",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/18",
		bottled: "11/22",
		price: "$92.99",
		state: "CA",
		retail: "ReserveBar",
		image: "jaq-r-01.png"
	},

	{
		id: 218,
		name: "Rhody's Barrel Brotherhood",
		type: "Rye",
		barrel: "AMB-R-09",
		age: "5yrs 11mos",
		proof: "112.62",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "RI",
		retail: "",
		image: ""
	},

	{
		id: 219,
		name: "Sahara",
		type: "Rye",
		barrel: "KRY-542",
		age: "5yrs 10mos",
		proof: "82",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 220,
		name: "Santee Market & Liquor / BPWC",
		type: "Rye",
		barrel: "KRY-527",
		age: "6yrs 6mos",
		proof: "122.8",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "11/22",
		price: "$99.99",
		state: "CA",
		retail: "F&D Wine and Spirits",
		image: ""
	},

	{
		id: 221,
		name: "Seelbach's",
		type: "Rye",
		barrel: "I95-11",
		age: "5yrs",
		proof: "114.58",
		finish: "None",
		mashbill: "95/5",
		source: "MGP",
		distilled: "11/28/2016",
		bottled: "11/28/2021",
		price: "$99.00",
		state: "DC",
		retail: "",
		image: "i95-11.jpg"
	},

	{
		id: 222,
		name: "Spiegelworld",
		type: "Rye",
		barrel: "TNR-03",
		age: "4yrs 9mos",
		proof: "111.72",
		finish: "None",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "1/16",
		bottled: "10/21",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 223,
		name: "Staff of Hollywood Beverage",
		type: "Rye",
		barrel: "KRY-522",
		age: "6yrs 7mos",
		proof: "122.22",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "OR",
		retail: "",
		image: ""
	},

	{
		id: 224,
		name: "Stafford Beverages",
		type: "Rye",
		barrel: "KRY-535",
		age: "6yrs 7mos",
		proof: "122.42",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "12/22",
		price: "$89.95",
		state: "OR",
		retail: "",
		image: ""
	},

	{
		id: 225,
		name: "T8ke & Rare Bird 101",
		type: "Rye",
		barrel: "AMB-0-3",
		age: "5yrs 11mos",
		proof: "114.76",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
	},

	{
		id: 226,
		name: "T8ke for r/Bourbon",
		type: "Rye",
		barrel: "AMB-5",
		age: "5yrs",
		proof: "114.68",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "amb-5.jpg"
	},

	{
		id: 227,
		name: "Total Wine & More",
		type: "Rye",
		barrel: "KRY-561",
		age: "6yrs 7mos",
		proof: "120.84",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 228,
		name: "Trevor's Liquor",
		type: "Rye",
		barrel: "AMB-R-2",
		age: "5yrs 11mos",
		proof: "112.32",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "",
		image: "amb-r-2.jpg"
	},

	{
		id: 229,
		name: "Trevor's Liquor",
		type: "Rye",
		barrel: "KRY-564",
		age: "6yrs 1mos",
		proof: "122.3",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Trevor's",
		image: "kry-564.jpg"
	},

	{
		id: 230,
		name: "Trevor's Liquor",
		type: "Rye",
		barrel: "WP-R-0",
		age: "6yrs 3mos",
		proof: "113.74",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "",
		image: ""
	},

	{
		id: 231,
		name: "Velvet Monkey",
		type: "Rye",
		barrel: "WP-R-2-A",
		age: "6yrs 2mos",
		proof: "114.18",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 232,
		name: "Velvet Monkey",
		type: "Rye",
		barrel: "WP-R-2-B",
		age: "6yrs 2mos",
		proof: "114.18",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
	},

	{
		id: 233,
		name: "Vintage Wine and Spirits",
		type: "Rye",
		barrel: "",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 234,
		name: "William Elliott",
		type: "Rye",
		barrel: "RHY-17-A",
		age: "",
		proof: "103",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NY",
		retail: "",
		image: ""
	},

	{
		id: 235,
		name: "Unknown",
		type: "Rye",
		barrel: "KRY-538",
		age: "6yrs Xmos",
		proof: "119.82",
		finish: "None",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 236,
		name: "Unknown",
		type: "Rye",
		barrel: "",
		age: "",
		proof: "",
		finish: "Barbados Rum",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 237,
		name: "Life of Luxe",
		type: "Exceptional",
		barrel: "81005",
		age: "14yrs 5mos",
		proof: "121.6",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "May/2008",
		bottled: "Dec/2022",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 238,
		name: "K&L Wine Merchants",
		type: "Exceptional",
		barrel: "E-KB-05",
		age: "9yrs",
		proof: "122",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "Oct/2013",
		bottled: "Nov/2022",
		price: "$169.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "e-kb-05.jpg"
	},

	{
		id: 239,
		name: "Unknown",
		type: "Exceptional",
		barrel: "E-M11-01",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "$199.99",
		state: "MA",
		retail: "Lighthouse Wine & Spirits",
		image: ""
	},

	{
		id: 240,
		name: "Mr Whiskers",
		type: "Exceptional",
		barrel: "E-M11-06",
		age: "10yrs 10mos",
		proof: "101.18",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "Feb/2011",
		bottled: "Dec/2022",
		price: "",
		state: "TN",
		retail: "Mr Whiskers Wines & Liquors",
		image: ""
	},

	{
		id: 241,
		name: "Commonwealth of Massachusetts",
		type: "Exceptional",
		barrel: "E-M11-15",
		age: "11yrs 8mos",
		proof: "104.86",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "Mar/2011",
		bottled: "Dec/2022",
		price: "$129.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: ""
	},

	{
		id: 242,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Exceptional",
		barrel: "E-M14-47",
		age: "14yrs 5mos",
		proof: "133.8",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "May/2008",
		bottled: "Dec/2022",
		price: "$199.99",
		state: "MA",
		retail: "Liquor Junction",
		image: ""
	},

	{
		id: 243,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Exceptional",
		barrel: "E-M14-54",
		age: "14yrs 5mos",
		proof: "135",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "May/2008",
		bottled: "Dec/2022",
		price: "$199.99",
		state: "MA",
		retail: "Liquor Junction",
		image: ""
	},

	{
		id: 244,
		name: "Commonwealth of Massachusetts",
		type: "Exceptional",
		barrel: "E-M14-55",
		age: "14yrs 5mos",
		proof: "135.52",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "May/2023",
		bottled: "Dec/2022",
		price: "$184.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: ""
	},

	{
		id: 245,
		name: "Gordon's",
		type: "Exceptional",
		barrel: "E-M9-28",
		age: "9yrs",
		proof: "131.9",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "Apr/2014",
		bottled: "Dec/2022",
		price: "$114.99",
		state: "MA",
		retail: "Gordon's Wine",
		image: ""
	},

	{
		id: 246,
		name: "Commonwealth of Massachusetts",
		type: "Exceptional",
		barrel: "E-M9-35",
		age: "9yrs 6mos",
		proof: "132.04",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "Apr/2013",
		bottled: "Feb/2023",
		price: "$109.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: ""
		},

	{
		id: 247,
		name: "Joe C with No Us Without You",
		type: "Exceptional",
		barrel: "EM-8-101",
		age: "8yrs 6mos",
		proof: "131.26",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "Apr/2014",
		bottled: "Nov/2022",
		price: "$99.50",
		state: "CA",
		retail: "Everson Royce",
		image: "em-8-101.jpg"
	},

	{
		id: 248,
		name: "The Vineyard",
		type: "Exceptional",
		barrel: "M-45",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NJ",
		retail: "The Vineyard Wines and Liquor",
		image: ""
	},

	{
		id: 249,
		name: "Justin's House of Bourbon",
		type: "Exceptional",
		barrel: "",
		age: "14yrs",
		proof: "133.8",
		finish: "None",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Justin's House of Bourbon",
		image: ""
	},

	{
		id: 250,
		name: "Unknown",
		type: "Exceptional",
		barrel: "",
		age: "",
		proof: "",
		finish: "Cognac",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 251,
		name: "Unknown",
		type: "Exceptional",
		barrel: "",
		age: "",
		proof: "",
		finish: "Barbados Rum",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 252,
		name: "Unknown",
		type: "Exceptional",
		barrel: "",
		age: "",
		proof: "",
		finish: "Madeira",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 253,
		name: "Unknown",
		type: "Exceptional",
		barrel: "",
		age: "",
		proof: "",
		finish: "Armagnac",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},

	{
		id: 254,
		name: "The Rite Selection",
		type: "Bourbon",
		barrel: "MAD-B-09",
		age: "6yrs 7mos",
		proof: "114.5",
		finish: "Madeira",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "$84.99",
		state: "NJ",
		retail: "Buy Rite",
		image: ""
	},

	{
		id: 255,
		name: "Joe Canal's / Benash Liquors",
		type: "Bourbon",
		barrel: "OLS-B-03",
		age: "6yrs 5mos",
		proof: "112.06",
		finish: "Oloroso",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "$89.99",
		state: "NJ",
		retail: "Joe Canal's & Benash Liquors",
		image: ""
	},

	{
		id: 256,
		name: "The Rite Selection",
		type: "Rye",
		barrel: "KRY-549",
		age: "6yrs 6mos",
		proof: "121.18",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$84.99",
		state: "NJ",
		retail: "Buy Rite",
		image: ""
	},

	{
		id: 257,
		name: "Joe Canal's / Benash Liquors",
		type: "Rye",
		barrel: "KRY-518",
		age: "6yrs 7mos",
		proof: "115.18",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$89.99",
		state: "NJ",
		retail: "Joe Canal's & Benash Liquors",
		image: ""
	}
];

// Check for id parameter in URL
var urlParams = new URLSearchParams(window.location.search);
var release = urlParams.get('id');

if (release) {
    // Filter items based on release id
    var filteredItems = items.filter(function(item) {
        return item.id == release;
    });

    // Display filtered items
    var itemList = document.getElementById("item-list");
    itemList.innerHTML = "";

    for (var i = 0; i < filteredItems.length; i++) {
        var item = filteredItems[i];
        var itemDiv = document.createElement("div");
        itemDiv.classList.add("card");
        itemDiv.innerHTML = `
            <h2>${item.name}</h2>
            <div class="card-content">
                <div class="card-image">
                    ${item.image ? `<img src="images/${item.image}" width="100" height="100">` : ""}
                </div>
                <div class="card-text">
                    ${item.barrel}<br>
                    ${item.type}<br>
                    ${item.finish}
                </div>
            </div>
            <a href="index.html">Back</a>
        `;
        itemList.appendChild(itemDiv);

        // Add click event listener to the card element
        itemDiv.addEventListener("click", function() {
            viewItemDetails(item.id);
        });
    }
} else {
var itemList = document.getElementById("item-list");
var countElement = document.createElement("div");
countElement.innerHTML = `Showing ${items.length} items`;
itemList.insertBefore(countElement, itemList.firstChild);
items.sort((a, b) => a.name.localeCompare(b.name));

for (var i = 0; i < items.length; i++) {
	var item = items[i];
	var itemDiv = document.createElement("div");
	itemDiv.classList.add("card");
	itemDiv.innerHTML = `
	
    <h2>${item.name}</h2>
	<div class="card-content">
	<div class="card-image">
        ${item.image ? `<img src="images/${item.image}" width="100" height="100">` : ""}
    </div>
	<div class="card-text">
    ${item.barrel}<br>
    ${item.type}<br>
    ${item.finish}
	</div>
	</div>
    <a href="javascript:viewItemDetails(${item.id})">View Details</a>
	</div>
	`;
	itemList.appendChild(itemDiv);

	// Add click event listener to the card element
	itemDiv.addEventListener("click", (function(itemCopy) {
		return function() {
			viewItemDetails(itemCopy.id);
		}
	})(item));
}

function filterItems() {
	var finishFilter = document.getElementById("finish-filter").value;
  
	if (finishFilter === "") {
	  // Show all items if no filters are selected
	  showAllItems();
	} else {
	  // Filter items based on selected finish
	  var filteredItems = items.filter(function (item) {
		return item.finish.toLowerCase().indexOf(finishFilter.toLowerCase()) !== -1;
	  });
	  updateItemList(filteredItems);
	}
}

function filterItemsByType(type) {
	var filteredItems;
	if (type === '') {
	  filteredItems = items;
	} else {
	  filteredItems = items.filter(function(item) {
		return item.type === type;
	  });
	}
	updateItemList(filteredItems);
}


function showAllItems() {
	updateItemList(items);
}

function updateItemList(updatedItems) {
	var itemList = document.getElementById("item-list");
	itemList.innerHTML = "";

	var count = updatedItems.length;
	var countDiv = document.createElement("div");
	countDiv.innerHTML = "Total Items: " + count;
	itemList.appendChild(countDiv);

	for (var i = 0; i < updatedItems.length; i++) {
		var item = updatedItems[i];
		var itemDiv = document.createElement("div");
		itemDiv.classList.add("card");
		itemDiv.innerHTML = `
    		<h2>${item.name}</h2>
			<div class="card-content">
			<div class="card-image">
        		${item.image ? `<img src="images/${item.image}" width="100" height="100">` : ""}
    		</div>
			<div class="card-text">
    			${item.barrel}<br>
    			${item.type}<br>
    			${item.finish}
			</div>
			</div>
    		<a href="javascript:viewItemDetails(${item.id})">View Details</a>
			</div>
			`;
		itemList.appendChild(itemDiv);
	  }
}


// GENERATE LINK TO DETAILS PAGE
function viewItemDetails(itemId) {
	window.location.href = "details.html?id=" + itemId;
}
}