var items = [
	{
		id: 1,
		name: "@WhiskyVegas",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "OLS-B-1",
		age: "6yrs 1mo",
		proof: "119.34",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "ols-b-1.jpg",
		label: "ols-b-1-l.jpg"
	},

	{
		id: 2,
		name: "Alec Bradley",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-289",
		age: "6yrs 4mos",
		proof: "116.62",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "rio-289.jpg",
		label: "rio-289-l.jpg"
	},

	{
		id: 3,
		name: "Allocated Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-06",
		age: "4yrs 4mos",
		proof: "116.6",
		finish: "",
		mashbill: "",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.95",
		state: "CA",
		retail: "Top Bourbon",
		image: "i21-06.jpg",
		label: "i21-06-l.jpg"
	},

	{
		id: 4,
		name: "Bar Keeper",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-42-A",
		age: "5yrs",
		proof: "120.76",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "irt-42a-l.jpg"
	},

	{
		id: 5,
		name: "Barrels & Brews",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-06",
		age: "5yrs 6mos",
		proof: "117.98",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 6,
		name: "Big Corks Germantown",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-26",
		age: "5yrs 6mos",
		proof: "117.42",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Corks Wine & Spirits",
		image: "",
		label: "irt-26-l.jpg"
	},

	{
		id: 7,
		name: "Bourbon Buddy",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-248",
		age: "6yrs",
		proof: "113.7",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "rio-248-l.jpg"
	},

	{
		id: 8,
		name: "Bourbon Enthusiast",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-223",
		age: "5yrs 9mos",
		proof: "115.8",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "Royal Batch",
		image: "rio-223.jpg",
		label: "rio-223-l.jpg"
	},

	{
		id: 9,
		name: "Bourbon Junkies",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "CC-2",
		age: "6yrs 2mos",
		proof: "117.4",
		finish: "Cognac",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "cc2.jpg",
		label: "cc2-l.jpg"
	},

	{
		id: 10,
		name: "Bourbon Junkies",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-209",
		age: "6yrs 1mo",
		proof: "117.86",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-209.jpg",
		label: "rio-209-l.jpg"
	},

	{
		id: 11,
		name: "Bourbons Bistro",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-55",
		age: "5yrs 4mos",
		proof: "122.64",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: "irt-55-l.jpg"
	},

	{
		id: 12,
		name: "Burlington Wine & Spirits",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-227",
		age: "6yrs 7mos",
		proof: "115.58",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "12/22",
		price: "$79.99",
		state: "MA",
		retail: "Burlington Wine & Spirits",
		image: "",
		label: "rio-227-l.jpg"
	},

	{
		id: 13,
		name: "Buster's Liquor & Wine",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-15",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$71.99",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: "",
		label: ""
	},

	{
		id: 14,
		name: "Buster's Liquor & Wine",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-228",
		age: "6yrs 6mos",
		proof: "114.1",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$81.99",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: "",
		label: "rio-228-l.jpg"
	},

	{
		id: 15,
		name: "Casa Fuente",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "OLS-B-2",
		age: "6yrs 5mos",
		proof: "110.78",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "ols-b-2-l.jpg"
	},

	{
		id: 16,
		name: "Cask",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-33",
		age: "5yrs 11mos",
		proof: "117.7",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "irt-33-l.jpg"
	},

	{
		id: 17,
		name: "Chasing Bourbon",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-287",
		age: "6yrs 6mos",
		proof: "115.64",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "",
		label: "rio-287-l.jpg"
	},

	{
		id: 18,
		name: "Chestnut Club",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-44",
		age: "5yrs",
		proof: "121.84",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "12/13/16",
		bottled: "11/12/21",
		price: "",
		state: "CA",
		retail: "",
		image: "irt-44.jpg",
		label: "irt-44-l.jpg"
	},

	{
		id: 19,
		name: "Chinglish",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-296",
		age: "5yrs 7mos",
		proof: "93",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "rio-296-l.jpg"
	},

	{
		id: 20,
		name: "Chip's Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-222-C",
		age: "6yrs 1mo",
		proof: "115.6",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$74.99",
		state: "CA",
		retail: "Chip's Liquor",
		image: "rio-222c.jpg",
		label: "rio-222c-l.jpg"
	},

	{
		id: 21,
		name: "Corona Cigars",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-224",
		age: "6yrs 4mos",
		proof: "116.26",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "FL",
		retail: "",
		image: "",
		label: "rio-224-l.jpg"
	},

	{
		id: 22,
		name: "Cosmopolitan",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "MAD-B-05",
		age: "5yrs 5mos",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "4/2022",
		price: "",
		state: "NV",
		retail: "NFS",
		image: "",
		label: "mad-b-05-l.jpg"
	},

	{
		id: 23,
		name: "Cosmopolitan",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-269",
		age: "6yrs 7mos",
		proof: "112.64",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "NFS",
		image: "",
		label: "rio-269-l.jpg"
	},

	{
		id: 24,
		name: "Curiada",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-02",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CT",
		retail: "Curiada",
		image: "",
		label: "irt-02-l.jpg"
	},

	{
		id: 25,
		name: "Del Mesa Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-222-A",
		age: "6yrs 1mo",
		proof: "115.6",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$79.99",
		state: "CA",
		retail: "Del Mesa Liquor",
		image: "rio-222a.jpg",
		label: "rio-222a-l.jpg"
	},

	{
		id: 26,
		name: "Dion's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-238",
		age: "6yrs 7mos",
		proof: "113.42",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "MA",
		retail: "Dion's ",
		image: "",
		label: ""
	},

	{
		id: 27,
		name: "Dion's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-240",
		age: "6yrs 7mos",
		proof: "114.14",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "MA",
		retail: "Dion's",
		image: "",
		label: ""
	},

	{
		id: 28,
		name: "Eataly at Park MGM",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-242",
		age: "5yrs 10mos",
		proof: "94",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$120.00",
		state: "NV",
		retail: "Eataly",
		image: "",
		label: ""
	},

	{
		id: 29,
		name: "El Cerrito Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-25",
		age: "5yrs 6mos",
		proof: "117.22",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "5/22",
		price: "$75.00",
		state: "CA",
		retail: "El Cerrito",
		image: "irt-25.jpg",
		label: "irt-25-l.jpg"
	},

	{
		id: 30,
		name: "Elixir",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-51",
		age: "5yrs 10mos",
		proof: "120.78",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 31,
		name: "Ettan",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-205",
		age: "5yrs 9mos",
		proof: "90",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 32,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-243",
		age: "6yrs 2mos",
		proof: "104.58",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: "rio-243-l.jpg"
	},

	{
		id: 33,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-255",
		age: "6yrs 2mos",
		proof: "118.02",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: ""
	},

	{
		id: 34,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-03",
		age: "4yrs 7mos",
		proof: "114.94",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: "i21-03-l.jpg"
	},

	{
		id: 35,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-07",
		age: "",
		proof: "116.44",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: "i21-07-l.jpg"
	},

	{
		id: 36,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-09",
		age: "",
		proof: "116.2",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: "i21-09-l.jpg"
	},

	{
		id: 37,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-11",
		age: "",
		proof: "118.24",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: "i21-11-l.jpg"
	},

	{
		id: 38,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-14",
		age: "4yrs 9mos",
		proof: "116.86",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: "i21-14-l.jpg"
	},

	{
		id: 39,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-15",
		age: "",
		proof: "117.86",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: "i21-15-l.jpg"
	},

	{
		id: 40,
		name: "Eureka!",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-20",
		age: "4yrs 9mos",
		proof: "115.24",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: "",
		label: "i21-20-l.jpg"
	},

	{
		id: 41,
		name: "Fernside",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-239",
		age: "5yrs 10mos",
		proof: "113.92",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "rio-239-l.jpg"
	},

	{
		id: 42,
		name: "Founder's Choice",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-07",
		age: "5yrs 7mos",
		proof: "118.48",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/2016",
		bottled: "1/2022",
		price: "$69.99",
		state: "NY",
		retail: "Mash & Grape",
		image: "irt-07.jpg",
		label: "irt-07-l.jpg"
	},

	{
		id: 43,
		name: "Founder's Choice",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-20",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "NY",
		retail: "Mash & Grape",
		image: "irt-20.jpg",
		label: "irt-20-l.jpg"
	},

	{
		id: 44,
		name: "Founder's Choice",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-273",
		age: "5yrs 8mos",
		proof: "116.36",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/2016",
		bottled: "1/2022",
		price: "",
		state: "NY",
		retail: "",
		image: "rio-273.jpg",
		label: "rio-273-l.jpg"
	},

	{
		id: 45,
		name: "George Awad and the Neat Freaks",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "BAL-B-02",
		age: "5yrs 2mos",
		proof: "114.06",
		finish: "Balsamo",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "FL",
		retail: "Sunshine Liquor",
		image: "",
		label: "bal-b-02-l.jpg"
	},

	{
		id: 46,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-213",
		age: "6yrs",
		proof: "116.96",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "rio-213.jpg",
		label: "rio-213-l.jpg"
	},

	{
		id: 47,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-214",
		age: "",
		proof: "",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 48,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-260",
		age: "6yrs 6mos",
		proof: "112.24",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 49,
		name: "Good Lion",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-05",
		age: "5yrs 3mos",
		proof: "101",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "irt-05-l.jpg"
	},

	{
		id: 50,
		name: "Gordon's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-270",
		age: "6yrs 7mos",
		proof: "117.14",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "12/22",
		price: "$74.99",
		state: "MA",
		retail: "Gordon's Wine",
		image: "rio-270.jpg",
		label: "rio-270-l.jpg"
	},

	{
		id: 51,
		name: "Hatchet Hall",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-46",
		age: "",
		proof: "107.2",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 52,
		name: "Helix Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-222B",
		age: "6yrs 1mos",
		proof: "115.6",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$79.99",
		state: "CA",
		retail: "Bottle Broz",
		image: "rio-222b.jpg",
		label: "rio-222b-l.jpg"
	},

	{
		id: 53,
		name: "Heritage Selections",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-229",
		age: "5yrs 8mos",
		proof: "114.92",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/2016",
		bottled: "1/2022",
		price: "",
		state: "KY",
		retail: "",
		image: "rio-229.jpg",
		label: "rio-229-l.jpg"
	},

	{
		id: 54,
		name: "Heritage Selections",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-08",
		age: "4yrs 5mos",
		proof: "116.3",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: "i21-08-l.jpg"
	},

	{
		id: 55,
		name: "Hi-Time Wine Cellars",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-295",
		age: "5yrs 9mos",
		proof: "117.12",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Hi-Time Wine Cellars",
		image: "",
		label: ""
	},

	{
		id: 56,
		name: "Hotel Covington",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-265",
		age: "5yrs 8mos",
		proof: "117.96",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: "rio-265-l.jpg"
	},

	{
		id: 57,
		name: "Jarred Dooley",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-40",
		age: "5yrs",
		proof: "119.22",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/12/16",
		bottled: "11/12/21",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 58,
		name: "Joe C",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-27",
		age: "5yrs",
		proof: "116.66",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16/16",
		bottled: "11/28/21",
		price: "",
		state: "CA",
		retail: "Everson Royce",
		image: "irt-27.jpg",
		label: "irt-27-l.jpg"
	},

	{
		id: 59,
		name: "Joe C",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "JR-1 / KHT-02",
		age: "4yrs 11mos",
		proof: "118.48",
		finish: "Jamaican Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "4/22",
		price: "$103.00",
		state: "CA",
		retail: "Everson Royce",
		image: "",
		label: "jr-1-l.jpg"
	},

	{
		id: 60,
		name: "Joe C with No Us Without You",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-213-A",
		age: "6yrs",
		proof: "113.72",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$92.00",
		state: "CA",
		retail: "Everson Royce",
		image: "",
		label: "rio-213-a-l.jpg"
	},

	{
		id: 61,
		name: "Justin's House of Bourbon",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-256",
		age: "6yrs",
		proof: "118.34",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Justin's House of Bourbon",
		image: "",
		label: "rio-256-l.jpg"
	},

	{
		id: 62,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-21",
		age: "5yrs",
		proof: "119.68",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "irt-21.jpg",
		label: "irt-21-l.jpg"
	},

	{
		id: 63,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-24",
		age: "5yrs",
		proof: "119.68",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "irt-24.jpg",
		label: "irt-24-l.jpg"
	},

	{
		id: 64,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-234",
		age: "6yrs",
		proof: "115.44",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "rio-234.jpg",
		label: "rio-234-l.jpg"
	},

	{
		id: 65,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-254",
		age: "6yrs",
		proof: "112.86",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "rio-254.jpg",
		label: "rio-254-l.jpg"
	},

	{
		id: 66,
		name: "Khoury's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "WP-B-05",
		age: "6yrs 6mos",
		proof: "104.42",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "11/22",
		price: "",
		state: "NV",
		retail: "Khoury's",
		image: "",
		label: "wp-b-05-l.jpg"
	},

	{
		id: 67,
		name: "Khoury's Fine Wine",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-261",
		age: "6yrs",
		proof: "114.04",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Khoury's",
		image: "",
		label: "rio-261-l.jpg"
	},

	{
		id: 68,
		name: "Lake District Wine & Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-10",
		age: "5yrs 6mos",
		proof: "120.16",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: "irt-10-l.jpg"
	},

	{
		id: 69,
		name: "Laundry Room",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-16",
		age: "4yrs 6mos",
		proof: "96",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "NFS",
		image: "",
		label: "i21-16-l.jpg"
	},

	{
		id: 70,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-18",
		age: "5yrs 4mos",
		proof: "118.8",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: "",
		label: "irt-18z-l.jpg"
	},

	{
		id: 71,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "OLS-B-05",
		age: "5yrs 11mos",
		proof: "112.74",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: "",
		label: "ols-b-05-l.jpg"
	},

	{
		id: 72,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-232",
		age: "6yrs 5mos",
		proof: "112.84",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: "",
		label: "rio-232-l.jpg"
	},

	{
		id: 73,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-244",
		age: "5yrs 10mos",
		proof: "114.72",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: "",
		label: "rio-244-l.jpg"
	},

	{
		id: 74,
		name: "Life of Luxe",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-262",
		age: "6yrs",
		proof: "118.34",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "",
		label: "rio-262-l.jpg"
	},

	{
		id: 75,
		name: "Liquor Barn",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-38",
		age: "5yrs 1mo",
		proof: "118.26",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "12/16",
		bottled: "1/22",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: "",
		label: "irt-38-l.jpg"
	},

	{
		id: 76,
		name: "Liquor Barn",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-300",
		age: "5yrs 7mos",
		proof: "116.3",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: "",
		label: "rio-300-l.jpg"
	},

	{
		id: 77,
		name: "Liquor Barn",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-12",
		age: "4yrs 6mos",
		proof: "116.76",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: "",
		label: "i21-12-l.jpg"
	},

	{
		id: 78,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "OLS-B-04",
		age: "6yrs 7mos",
		proof: "110.1",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "12/22",
		price: "",
		state: "MA",
		retail: "Liquor Junction",
		image: "ols-b-04.jpg",
		label: "ols-b-04-l.jpg"
	},

	{
		id: 79,
		name: "LiquorLineup.com",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-219",
		age: "5yrs 7mos",
		proof: "117.74",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "NV",
		retail: "LiquorLineup.com",
		image: "",
		label: "rio-219-l.jpg"
	},

	{
		id: 80,
		name: "Littlebear Bottleshop",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-42B",
		age: "5yrs",
		proof: "120.76",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Littlebear Bottleshop",
		image: "",
		label: "irt-42b-l.jpg"
	},

	{
		id: 81,
		name: "Littlebear Bottleshop",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "OLS-B-06",
		age: "5yrs 6mos",
		proof: "110.78",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Littlebear Bottleshop",
		image: "ols-b06.jpg",
		label: "ols-b06-l.jpg"
	},

	{
		id: 82,
		name: "Local Feed",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-286-B",
		age: "",
		proof: "",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 83,
		name: "Lotus of Siam",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-204",
		age: "6yrs 1mo",
		proof: "95",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "rio-204-l.jpg"
	},

	{
		id: 84,
		name: "Lotus of Siam",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-226",
		age: "",
		proof: "",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 85,
		name: "Major League Bourbon Clubhouse",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "",
		age: "",
		proof: "",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 86,
		name: "Majority Rule",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-53",
		age: "5yrs 7mos",
		proof: "111.14",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: "irt-53-l.jpg"
	},

	{
		id: 87,
		name: "Mash & Journey Whiskey Club",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-290",
		age: "6yrs",
		proof: "113.54",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$82.99",
		state: "DC",
		retail: "",
		image: "",
		label: "rio-290-l.jpg"
	},

	{
		id: 88,
		name: "MGM Resorts",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-251",
		age: "6yrs 5mos",
		proof: "95",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "rio-251-l.jpg"
	},

	{
		id: 89,
		name: "Michael Mina",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-201",
		age: "5yrs 9mos",
		proof: "115.84",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "rio-201-l.jpg"
	},

	{
		id: 90,
		name: "Michael Mina",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-220",
		age: "",
		proof: "",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 91,
		name: "Michael Mina",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-283",
		age: "6yrs",
		proof: "104.24",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 92,
		name: "Michael P. Trow & Gia St. George Terry",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-211",
		age: "6yrs 5mos",
		proof: "95.4",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/2016",
		bottled: "10/2022",
		price: "",
		state: "NV",
		retail: "",
		image: "rio-211.jpg",
		label: "rio-211-l.jpg"
	},

	{
		id: 93,
		name: "Mission Wine & Spirits",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-30",
		age: "5yrs",
		proof: "119.58",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16/2016",
		bottled: "11/18/2021",
		price: "",
		state: "CA",
		retail: "",
		image: "irt-30.jpg",
		label: "irt-30-l.jpg"
	},

	{
		id: 94,
		name: "Mission Wine & Spirits",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-59",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "irt-59.jpg",
		label: "irt-59-l.jpg"
	},

	{
		id: 95,
		name: "Mister O's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-19-B",
		age: "5yrs 8mos",
		proof: "118.28",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 96,
		name: "Mixing Glass",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-12-B",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 97,
		name: "Mixing Glass",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-13-A",
		age: "4yrs 4mos",
		proof: "117.6",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "7/13/2017",
		bottled: "11/18/2021",
		price: "",
		state: "CA",
		retail: "",
		image: "i21-13a.jpg",
		label: "i21-13a-l.jpg"
	},

	{
		id: 98,
		name: "Moye O'Brien Bourbon Crew",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-218",
		age: "6yrs 4mos",
		proof: "114.78",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "rio-218-l.jpg"
	},

	{
		id: 99,
		name: "Mr Whiskers",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-03",
		age: "5yrs 11mos",
		proof: "119.74",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Mr Whiskers Wines & Liquors",
		image: "",
		label: "irt-3-l.jpg"
	},

	{
		id: 100,
		name: "Mr Whiskers",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-288",
		age: "",
		proof: "",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Mr Whiskers Wines & Liquors",
		image: "",
		label: ""
	},

	{
		id: 101,
		name: "Mythical",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "MAD-4",
		age: "5yrs",
		proof: "117.23",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "",
		retail: "",
		image: "",
		label: "mad-4-l.jpg"
	},

	{
		id: 102,
		name: "Nashville Daily",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-41",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 103,
		name: "OBC Kitchen",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-13-B",
		age: "4yrs 4mos",
		proof: "117.6",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "7/17",
		bottled: "11/21",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: "i21-13b-l.jpg"
	},

	{
		id: 104,
		name: "Old Man Bar",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-18",
		age: "4yrs 4mos",
		proof: "116.14",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "7/13/2017",
		bottled: "11/12/2021",
		price: "",
		state: "CA",
		retail: "",
		image: "irt-18.jpg",
		label: "irt-18-l.jpg"
	},

	{
		id: 105,
		name: "Old Man Bar",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-46",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 106,
		name: "Old Man Bar",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-18",
		age: "",
		proof: "",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 107,
		name: "On The Thirty",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-19-A",
		age: "5yrs 2mos",
		proof: "118.28",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 108,
		name: "Obliteration",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "Unicorn",
		age: "14yrs",
		proof: "143.8",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$599.99",
		state: "DC",
		retail: "Seelbach's",
		image: "obliteration.jpg",
		label: "obliteration-l.jpg"
	},

	{
		id: 109,
		name: "Pacifica Hotels",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "I21-01",
		age: "",
		proof: "90",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 110,
		name: "Party Source",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-259",
		age: "5yrs 9mos",
		proof: "117.12",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 111,
		name: "Prime Barrel",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-235",
		age: "6yrs 6mos",
		proof: "113.18",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.00",
		state: "NY",
		retail: "De Wine Spot",
		image: "rio-235.jpg",
		label: "rio-235-l.jpg"
	},

	{
		id: 112,
		name: "Raised by Wolves",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-34",
		age: "5yrs 1 mo",
		proof: "116.26",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "12/2016",
		bottled: "1/2022",
		price: "",
		state: "CA",
		retail: "Bar Cart",
		image: "irt-34.jpg",
		label: "irt-34-l.jpg"
	},

	{
		id: 113,
		name: "Rapid Liquors",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-236",
		age: "6yrs 7mos",
		proof: "114.12",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$68.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: "",
		label: "rio-236-l.jpg"
	},

	{
		id: 114,
		name: "Rare Bird 101",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-241",
		age: "",
		proof: "",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 115,
		name: "Raymond 1886",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-297",
		age: "",
		proof: "",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 116,
		name: "Red Dog",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-17",
		age: "5yrs 6mos",
		proof: "117.66",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "TN",
		retail: "Red Dog",
		image: "",
		label: "irt-17-l.jpg"
	},

	{
		id: 117,
		name: "Red Dog",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "JR-B-02",
		age: "4yrs 10mos",
		proof: "118.48",
		finish: "Jamaican Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "TN",
		retail: "Red Dog",
		image: "jr-b-02.jpg",
		label: "jr-b-02-l.jpg"
	},

	{
		id: 118,
		name: "Red Dog",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "WP-B-04",
		age: "5yrs",
		proof: "110.82",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$109.99",
		state: "TN",
		retail: "Red Dog",
		image: "wp-b-04.jpg",
		label: "wp-b-04-l.jpg"
	},

	{
		id: 119,
		name: "Redbird",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-278",
		age: "6yrs",
		proof: "114.8",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "rio-278-l.jpg"
	},

	{
		id: 120,
		name: "Republique",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-264",
		age: "5yrs 3mos",
		proof: "113.68",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "May 2016",
		bottled: "Jan 2022",
		price: "",
		state: "CA",
		retail: "Republique",
		image: "",
		label: "rio-264-l.jpg"
	},

	{
		id: 121,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-25-2",
		age: "5yrs 4mos",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$114.99",
		state: "KY",
		retail: "",
		image: "",
		label: "irt-25-2-l.jpg"
	},

	{
		id: 122,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-36A",
		age: "6yrs",
		proof: "115.12",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 123,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-286-A",
		age: "6yrs",
		proof: "115.12",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: "rio-286a-l.jpg"
	},

	{
		id: 124,
		name: "Sahara Las Vegas",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-23",
		age: "5yrs",
		proof: "89.5",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "irt-23-l.jpg"
	},

	{
		id: 125,
		name: "Sahara Las Vegas",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "MAD-1",
		age: "5yrs",
		proof: "104",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "mad-1-l.jpg"
	},

	{
		id: 126,
		name: "Sand Dollar",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-298",
		age: "6yrs 5mos",
		proof: "113.02",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "rio-298-l.jpg"
	},

	{
		id: 127,
		name: "Santee Market & Liquor / BPWC",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-13",
		age: "6yrs",
		proof: "117.72",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "11/22",
		price: "$79.99",
		state: "CA",
		retail: "F&D Wine and Spirits",
		image: "",
		label: "irt-13-l.jpg"
	},

	{
		id: 128,
		name: "Scopa Italian Roots",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-22",
		age: "5yrs",
		proof: "119.18",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 129,
		name: "Seelbach's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-35",
		age: "5yrs",
		proof: "117.32",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: "irt-35.jpg",
		label: "irt-35-l.jpg"
	},

	{
		id: 130,
		name: "Seelbach's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-60",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "",
		label: ""
	},

	{
		id: 131,
		name: "Seelbach's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "MAD-B-1",
		age: "5yrs",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: "mad-b-1.jpg",
		label: "mad-b-1-l.jpg"
	},

	{
		id: 132,
		name: "Seelbach's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "WP-1",
		age: "6yrs 7mos",
		proof: "113.48",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: "wp-1.jpg",
		label: "wp-1-l.jpg"
	},

	{
		id: 133,
		name: "Seelbach's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-202",
		age: "6yrs",
		proof: "115.52",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-202.jpg",
		label: "rio-202-l.jpg"
	},

	{
		id: 134,
		name: "Seelbach's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-252",
		age: "6yrs",
		proof: "113.62",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-252.jpg",
		label: "rio-252-l.jpg"
	},

	{
		id: 135,
		name: "Seelbach's",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-267",
		age: "6yrs",
		proof: "114.78",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-267.jpg",
		label: "rio-267-l.jpg"
	},

	{
		id: 136,
		name: "Seelbach's & Bourbon Enthusiast",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "WP-B-2",
		age: "5yrs",
		proof: "109.26",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "6/22",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: "wp-b-2.jpg",
		label: "wp-b-2-l.jpg"
	},

	{
		id: 137,
		name: "Sinkers Wine & Spirits",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-282",
		age: "6yrs 2mos",
		proof: "118.2",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: "rio-282-l.jpg"
	},

	{
		id: 138,
		name: "Southern Arizona Whiskey Society",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "WP-B-03",
		age: "5yrs 6mos",
		proof: "111.1",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "AZ",
		retail: "Batch",
		image: "wp-b-03.jpg",
		label: "wp-b-03-l.jpg"
	},

	{
		id: 139,
		name: "Southern Whiskey Society",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-54",
		age: "5yrs 7mos",
		proof: "102.6",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/2016",
		bottled: "6/2022",
		price: "$69.99",
		state: "TN",
		retail: "Red Dog",
		image: "irt-54.jpg",
		label: "irt-54-l.jpg"
	},

	{
		id: 141,
		name: "Spiegelworld",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-31",
		age: "5yrs 7mos",
		proof: "95",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "6/22",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: "",
		label: "irt-31-l.jpg"
	},

	{
		id: 142,
		name: "Spiegelworld",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "KHT-22",
		age: "5yrs",
		proof: "59.11",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: "",
		label: "kht-22-l.jpg"
	},

	{
		id: 143,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-29",
		age: "5yrs 6mos",
		proof: "116.88",
		finish: "PX Sherry",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: "irt-29.jpg",
		label: "irt-29-l.jpg"
	},

	{
		id: 144,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-215",
		age: "5yrs 8mos",
		proof: "112.52",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "rio-215.jpg",
		label: "rio-215-l.jpg"
	},

	{
		id: 145,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-221",
		age: "5yrs 8mos",
		proof: "115.52",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "DC",
		retail: "",
		image: "",
		label: "rio-221-l.jpg"
	},

	{
		id: 146,
		name: "Thunderbolt",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-11",
		age: "5yrs",
		proof: "90",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 147,
		name: "Top's Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "MAD-2",
		age: "5yrs",
		proof: "112.34",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Top's Liquor",
		image: "",
		label: "mad-2-l.jpg"
	},

	{
		id: 148,
		name: "Top's Liquor",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-206",
		age: "6yrs 5mos",
		proof: "113.02",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Top's Liquor",
		image: "",
		label: "rio-206-l.jpg"
	},

	{
		id: 149,
		name: "Total Wine & More",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "FSR-B-02",
		age: "6yrs 7mos",
		proof: "110.34",
		finish: "Barbados Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 150,
		name: "Trevor's Liquors",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-212",
		age: "6yrs 1mos",
		proof: "115.52",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Trevor's Liquors",
		image: "",
		label: ""
	},

	{
		id: 151,
		name: "Vintage Corks",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-09",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 152,
		name: "Vintage Corks",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-28",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 153,
		name: "Vintage Corks",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-287",
		age: "",
		proof: "",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 154,
		name: "Westport Whiskey & Wine",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-249",
		age: "5yrs 7mos",
		proof: "114.18",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "rio-249.jpg",
		label: "rio-249-l.jpg"
	},

	{
		id: 155,
		name: "Whiskey Locator",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-299",
		age: "6yrs",
		proof: "118.48",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "rio-299.jpg",
		label: "rio-299-l.jpg"
	},

	{
		id: 156,
		name: "Wine Chap",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-32",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "irt-32.jpg",
		label: "irt-32-l.jpg"
	},

	{
		id: 157,
		name: "Wine Chap",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-207",
		age: "6yrs 5mos",
		proof: "114.48",
		finish: "",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "rio-207.jpg",
		label: "rio-207-l.jpg"
	},

	{
		id: 158,
		name: "Winston House",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-37",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "irt-37-l.jpg"
	},

	{
		id: 159,
		name: "Winston House",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "IRT-45",
		age: "",
		proof: "",
		finish: "",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "irt-45-l.jpg"
	},

	{
		id: 160,
		name: "Unknown",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "",
		age: "",
		proof: "",
		finish: "Eucalipto",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 161,
		name: "Accomplice Bar",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "I95-07",
		age: "",
		proof: "",
		finish: "",
		mashbill: "95/5",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 162,
		name: "ADHD Fishing",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-547",
		age: "6yrs 6mos",
		proof: "121.2",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "kry-547.jpg",
		label: "kry-547-l.jpg"
	},

	{
		id: 163,
		name: "Allocated Liquor",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "I95-14",
		age: "5yrs",
		proof: "113.94",
		finish: "",
		mashbill: "95/5",
		source: "MGP",
		distilled: "11/28/2016",
		bottled: "11/28/2021",
		price: "$69.95",
		state: "CA",
		retail: "Top Bourbon",
		image: "i95-14.jpg",
		label: "i95-14-l.jpg"
	},

	{
		id: 164,
		name: "Aman's",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-534-B",
		age: "7rys 4mos",
		proof: "122.7",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "WI",
		retail: "Aman's",
		image: "kry-534b.jpg",
		label: "kry-534b-l.jpg"
	},

	{
		id: 165,
		name: "Barrels & Brews",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-545",
		age: "",
		proof: "",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 166,
		name: "Bayway World of Liquor",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-R-19",
		age: "6yrs 6mos",
		proof: "112.06",
		finish: "Amburana",
		mashbill: "95/5",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "NJ",
		retail: "Bayway",
		image: "amb-r-19.jpg",
		label: "amb-r-19-l.jpg"
	},

	{
		id: 167,
		name: "Born & Raised",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "I95-10",
		age: "4yrs 4mos",
		proof: "113.8",
		finish: "",
		mashbill: "",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "i95-10-l.jpg"
	},

	{
		id: 168,
		name: "Bourbon Outfitter",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-04",
		age: "5yrs 7mos",
		proof: "113.64",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Bourbon Outfitter",
		image: "amb4.jpg",
		label: "amb4-l.jpg"
	},

	{
		id: 169,
		name: "Bourbon Pursuit Podcast",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-567",
		age: "6yrs 1mos",
		proof: "121.68",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "kry-567.jpg",
		label: "kry-567-l.jpg"
	},

	{
		id: 170,
		name: "Brown Jug",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-03-A",
		age: "5yrs 7mos",
		proof: "115.78",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "AK",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 171,
		name: "Buster's Liquor & Wine",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "I95-17",
		age: "5yrs 6mos",
		proof: "115.06",
		finish: "",
		mashbill: "",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: "i95-17..png",
		label: "i95-17-l.jpg"
	},

	{
		id: 172,
		name: "Buster's Liquor & Wine",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-542-A",
		age: "6yrs 7mos",
		proof: "121.28",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: "",
		label: "kry-542-a-l.jpg"
	},

	{
		id: 173,
		name: "CH Projects",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "I95-10",
		age: "",
		proof: "",
		finish: "",
		mashbill: "95/5",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 174,
		name: "Chasing Bourbon",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-546",
		age: "6yrs 6mos",
		proof: "120.1",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "",
		label: "kry-546-l.jpg"
	},

	{
		id: 175,
		name: "Chicagoland Whiskey",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-564",
		age: "6yrs 1mo",
		proof: "122.6",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "",
		label: "kry-564zz-l.jpg"
	},

	{
		id: 176,
		name: "Cosmopolitan",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-R-03-A",
		age: "6yrs",
		proof: "115.8",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "NFS",
		image: "",
		label: "amb-r-03-a-l.jpg"
	},

	{
		id: 177,
		name: "Cosmopolitan",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-530",
		age: "6yrs 7mos",
		proof: "122",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/2016",
		bottled: "12/2022",
		price: "",
		state: "NV",
		retail: "NFS",
		image: "",
		label: "kry-530-l.jpg"
	},

	{
		id: 178,
		name: "Dama",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-08",
		age: "5yrs 6mos",
		proof: "111.42",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "tnr-08-l.jpg"
	},

	{
		id: 179,
		name: "El Cerrito",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-569",
		age: "6yrs 6mos",
		proof: "121.04",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "11/22",
		price: "$95.00",
		state: "CA",
		retail: "El Cerrito",
		image: "kry-569.jpg",
		label: "kry-569-l.jpg"
	},

	{
		id: 180,
		name: "Elixir",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-570",
		age: "7yrs 4mos",
		proof: "122.1",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/15",
		bottled: "9/22",
		price: "",
		state: "TN",
		retail: "",
		image: "kry-570.jpg",
		label: "kry-570-l.jpg"
	},

	{
		id: 181,
		name: "Eureka!",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-529",
		age: "6yrs 5mos",
		proof: "121.88",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "kry-529-l.jpg"
	},

	{
		id: 182,
		name: "Eureka!",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-541",
		age: "6yrs 5mos",
		proof: "121.88",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "kry-541-l.jpg"
	},

	{
		id: 183,
		name: "Evel Pie",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "RHY-7B",
		age: "4yrs 9mos",
		proof: "103",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "rhy-7b-l.jpg"
	},

	{
		id: 185,
		name: "Founder's Choice",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "RHY-20",
		age: "4yrs 4mos",
		proof: "115.88",
		finish: "",
		mashbill: "51/45/4",
		source: "",
		distilled: "9/17",
		bottled: "1/22",
		price: "$59.99",
		state: "NY",
		retail: "Mash & Grape",
		image: "rhy-20.jpg",
		label: "rhy-20-l.jpg"
	},

	{
		id: 186,
		name: "G & R Embry",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "RHY-17-B",
		age: "4yrs 2mos",
		proof: "101",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NY",
		retail: "NFS",
		image: "",
		label: "rhy-17b-l.jpg"
	},

	{
		id: 187,
		name: "Golden Tiki",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "RHY-7-A",
		age: "4yrs 9mos",
		proof: "103",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "rhy-7a-l.jpg"
	},

	{
		id: 188,
		name: "Gordon's",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "",
		age: "",
		proof: "",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "MA",
		retail: "Gordon's Wine",
		image: "",
		label: ""
	},

	{
		id: 189,
		name: "Gordon's",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-523",
		age: "6yrs 7mos",
		proof: "88.22",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "12/22",
		price: "$94.99",
		state: "MA",
		retail: "Gordon's Wine",
		image: "kry-523.jpg",
		label: "kry-523-l.jpg"
	},

	{
		id: 190,
		name: "Heritage Selections",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-565",
		age: "",
		proof: "",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 191,
		name: "Hi-Time Wine Cellars",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-02",
		age: "4yrs 3mos",
		proof: "111.46",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Hi-Time Wine Cellars",
		image: "",
		label: "tnr-02-l.jpg"
	},

	{
		id: 192,
		name: "Jarred Dooley",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-01",
		age: "",
		proof: "110.34",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 193,
		name: "Joe C",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "I95-15",
		age: "5yrs",
		proof: "113.08",
		finish: "",
		mashbill: "95/5",
		source: "MGP",
		distilled: "11/28/2016",
		bottled: "12/06/2021",
		price: "",
		state: "CA",
		retail: "Everson Royce",
		image: "i95-15.jpg",
		label: "i95-15-l.jpg"
	},

	{
		id: 194,
		name: "K&L Wine Merchants",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-04",
		age: "5yrs 6mos",
		proof: "110.62",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "1/12/2016",
		bottled: "10/15/2021",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "tnr-04.jpg",
		label: "tnr-04-l.jpg"
	},

	{
		id: 195,
		name: "K&L Wine Merchants",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-07",
		age: "5yrs 6mos",
		proof: "111",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "tnr-07.jpg",
		label: "tnr-07-l.jpg"
	},

	{
		id: 196,
		name: "Keg n Bottle & Rare Bird 101",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "101-95",
		age: "5yrs 9mos",
		proof: "113.16",
		finish: "PX Sherry",
		mashbill: "95/5",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Keg n Bottle",
		image: "101-95.jpg",
		label: "101-95-l.jpg"
	},

	{
		id: 197,
		name: "Khoury's Fine Wine",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-10",
		age: "5yrs 6mos",
		proof: "109.42",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Khoury's",
		image: "",
		label: "tnr-10-l.jpg"
	},

	{
		id: 198,
		name: "Last Chance Liquors",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-573",
		age: "6yrs 7mos",
		proof: "122.82",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "12/22",
		price: "",
		state: "TN",
		retail: "Last Chance Liquors",
		image: "",
		label: ""
	},

	{
		id: 199,
		name: "Lee's Discount Liquor",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "EUC-B-1",
		age: "5yrs",
		proof: "115.1",
		finish: "Eucalipto",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "June 2022",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: "",
		label: "euc-b-1-l.jpg"
	},

	{
		id: 200,
		name: "Liquor Depot",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-568",
		age: "6yrs 7mos",
		proof: "121.16",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "May 2016",
		bottled: "Dec 2022",
		price: "",
		state: "OR",
		retail: "Liquor Depot",
		image: "",
		label: ""
	},

	{
		id: 201,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-549-B",
		age: "6yrs 7mos",
		proof: "121.18",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "MA",
		retail: "Liquor Junction",
		image: "",
		label: "kry-549-l.jpg"
	},

	{
		id: 202,
		name: "LiquorLineup.com",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-564",
		age: "6yrs 2mos",
		proof: "122.5",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "7/22",
		price: "",
		state: "NV",
		retail: "LiquorLineup.com",
		image: "",
		label: "kry-564z-l.jpg"
	},

	{
		id: 203,
		name: "Littlebear Bottleshop",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-R-2-A",
		age: "6yrs",
		proof: "115.8",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Littlebear Bottleshop",
		image: "amb-r-2-a.jpg",
		label: "amb-r-2-a-l.jpg"
	},

	{
		id: 204,
		name: "Loch & K(e)y",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-526-A",
		age: "6yrs 7mos",
		proof: "121.04",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "MA",
		retail: "",
		image: "",
		label: "kry-526-a-l.jpg"
	},

	{
		id: 205,
		name: "Mina",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-05",
		age: "5yrs 5mos",
		proof: "112.24",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "tnr-05-l.jpg"
	},

	{
		id: 206,
		name: "Mythical",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-534-A",
		age: "7yrs 4mos",
		proof: "122.7",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "kry-534-a-l.jpg"
	},

	{
		id: 207,
		name: "Omni",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "",
		age: "",
		proof: "",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 208,
		name: "Pacific Cocktail Haven",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-548",
		age: "5yrs 10mos",
		proof: "122.1",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown ",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: "kry-548-l.jpg"
	},

	{
		id: 209,
		name: "Pacifica Hotels",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-06-B",
		age: "4yrs 6mos",
		proof: "112.4",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "7/17",
		bottled: "11/21",
		price: "",
		state: "CA",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 210,
		name: "Playa Provisions",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-06A",
		age: "6yrs",
		proof: "112.4",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: "tnr-06a.jpg",
		label: "tnr-06a-l.jpg"
	},

	{
		id: 211,
		name: "Prime Barrel",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-521",
		age: "6yrs 6mos",
		proof: "119.76",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$85.00",
		state: "NY",
		retail: "De Wine Spot",
		image: "kry-521.jpg",
		label: "kry-521-l.jpg"
	},

	{
		id: 212,
		name: "Rapid Liquors",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-557-A",
		age: "6yrs 7mos",
		proof: "122.06",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "MA",
		retail: "",
		image: "",
		label: "kry-557-a-l.jpg"
	},

	{
		id: 213,
		name: "Rare Bird 101",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-544",
		age: "6yrs 4mos",
		proof: "120.3",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "kry-544.jpg",
		label: "kry-544-l.jpg"
	},

	{
		id: 214,
		name: "Red Dog",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-561",
		age: "5yrs 11mos",
		proof: "117.98",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "TN",
		retail: "Red Dog",
		image: "",
		label: "kry-561-l.jpg"
	},

	{
		id: 215,
		name: "Republique",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-524",
		age: "6yrs 5mos",
		proof: "121.86",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "May 2016",
		bottled: "Oct 2022",
		price: "",
		state: "CA",
		retail: "Republique",
		image: "",
		label: "kry-524-l.jpg"
	},

	{
		id: 216,
		name: "ReserveBar TopFlight Series",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-R-06",
		age: "5yrs 11mos",
		proof: "115.28",
		finish: "Amburana",
		mashbill: "51/45/4",
		source: "Bardstown",
		distilled: "12/16",
		bottled: "11/22",
		price: "$92.99",
		state: "CA",
		retail: "ReserveBar",
		image: "amb-r-06.png",
		label: "amb-r-06-l.jpg"
	},

	{
		id: 217,
		name: "ReserveBar TopFlight Series",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "JAQ-R-01",
		age: "4yrs 6mos",
		proof: "113.3",
		finish: "Jaqueira",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/18",
		bottled: "11/22",
		price: "$92.99",
		state: "CA",
		retail: "ReserveBar",
		image: "jaq-r-01.png",
		label: "jaq-r-01-l.jpg"
	},

	{
		id: 218,
		name: "Rhody's Barrel Brotherhood",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-R-09",
		age: "5yrs 11mos",
		proof: "112.62",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "RI",
		retail: "",
		image: "",
		label: "amb-r-09-l.jpg"
	},

	{
		id: 219,
		name: "Sahara",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-542",
		age: "5yrs 10mos",
		proof: "82",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "kry-542-l.jpg"
	},

	{
		id: 220,
		name: "Santee Market & Liquor / BPWC",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-527",
		age: "6yrs 6mos",
		proof: "122.8",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "11/22",
		price: "$99.99",
		state: "CA",
		retail: "F&D Wine and Spirits",
		image: "",
		label: "kry-527-l.jpg"
	},

	{
		id: 221,
		name: "Seelbach's",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "I95-11",
		age: "5yrs",
		proof: "114.58",
		finish: "",
		mashbill: "95/5",
		source: "MGP",
		distilled: "11/28/2016",
		bottled: "11/28/2021",
		price: "$99.00",
		state: "DC",
		retail: "",
		image: "i95-11.jpg",
		label: "i95-11-l.jpg"
	},

	{
		id: 222,
		name: "Spiegelworld",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "TNR-03",
		age: "4yrs 9mos",
		proof: "111.72",
		finish: "",
		mashbill: "95/5",
		source: "Dickel",
		distilled: "1/16",
		bottled: "10/21",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: "",
		label: "tnr-03-l.jpg"
	},

	{
		id: 223,
		name: "Staff of Hollywood Beverage",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-522",
		age: "6yrs 7mos",
		proof: "122.22",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "OR",
		retail: "",
		image: "kry-522.jpg",
		label: "kry-522-l.jpg"
	},

	{
		id: 224,
		name: "Stafford Beverages",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-535",
		age: "6yrs 7mos",
		proof: "122.42",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "5/16",
		bottled: "12/22",
		price: "$89.95",
		state: "OR",
		retail: "",
		image: "kry-535.jpg",
		label: "kry-535-l.jpg"
	},

	{
		id: 225,
		name: "T8ke & Rare Bird 101",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-R-03",
		age: "5yrs 11mos",
		proof: "114.76",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: "",
		label: "amb-r-03-l.jpg"
	},

	{
		id: 226,
		name: "T8ke for r/Bourbon",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-5",
		age: "5yrs",
		proof: "114.68",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: "amb-5.jpg",
		label: "amb-5-l.jpg"
	},

	{
		id: 227,
		name: "Total Wine & More",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-561",
		age: "6yrs 7mos",
		proof: "120.84",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "kry-561z-l.jpg"
	},

	{
		id: 228,
		name: "Trevor's Liquor",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "AMB-R-2",
		age: "5yrs 11mos",
		proof: "112.32",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "",
		image: "amb-r-2.jpg",
		label: "amb-r-2-l.jpg"
	},

	{
		id: 229,
		name: "Trevor's Liquor",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-564",
		age: "6yrs 1mos",
		proof: "122.3",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Trevor's",
		image: "kry-564.jpg",
		label: "kry-564-l.jpg"
	},

	{
		id: 230,
		name: "Trevor's Liquor",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "WP-B-01",
		age: "6yrs 3mos",
		proof: "113.74",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "",
		image: "wp-b-01.jpg",
		label: "wp-b-01-l.jpg"
	},

	{
		id: 231,
		name: "Velvet Monkey",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "WP-R-02-A",
		age: "6yrs 2mos",
		proof: "114.18",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "",
		label: "wp-r-02a.jpg"
	},

	{
		id: 232,
		name: "Velvet Monkey",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "WP-R-02-B",
		age: "6yrs 2mos",
		proof: "114.18",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: "wp-r-02-b.jpg",
		label: "wp-r-02-b-l.jpg"
	},

	{
		id: 233,
		name: "Vintage Wine and Spirits",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "",
		age: "",
		proof: "",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 234,
		name: "William Elliott",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "RHY-17-A",
		age: "",
		proof: "103",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NY",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 235,
		name: "Unknown",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-538",
		age: "6yrs Xmos",
		proof: "119.82",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 236,
		name: "Unknown",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "",
		age: "",
		proof: "",
		finish: "Barbados Rum",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "unknown-barbados-rum-l.jpg"
	},

	{
		id: 237,
		name: "Life of Luxe",
		type: "Malt",
		series: "Exceptional",
		barrel: "81005",
		age: "14yrs 5mos",
		proof: "121.6",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "May/2008",
		bottled: "Dec/2022",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 238,
		name: "K&L Wine Merchants",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-KB-05",
		age: "9yrs",
		proof: "122",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "Oct/2013",
		bottled: "Nov/2022",
		price: "$169.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: "e-kb-05.jpg",
		label: "e-kb-05-l.jpg"
	},

	{
		id: 239,
		name: "Unknown",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-M11-01",
		age: "",
		proof: "",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "$199.99",
		state: "MA",
		retail: "Lighthouse Wine & Spirits",
		image: "e-m11-01.jpg",
		label: "e-m11-01-l.jpg"
	},

	{
		id: 240,
		name: "Mr Whiskers",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-M11-06",
		age: "10yrs 10mos",
		proof: "101.18",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "Feb/2011",
		bottled: "Dec/2022",
		price: "",
		state: "TN",
		retail: "Mr Whiskers Wines & Liquors",
		image: "e-m11-06.jpg",
		label: "e-m11-06-l.jpg"
	},

	{
		id: 241,
		name: "Commonwealth of Massachusetts",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-M11-15",
		age: "11yrs 8mos",
		proof: "104.86",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "Mar/2011",
		bottled: "Dec/2022",
		price: "$129.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: "",
		label: ""
	},

	{
		id: 242,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-M14-47",
		age: "14yrs 5mos",
		proof: "133.8",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "May/2008",
		bottled: "Dec/2022",
		price: "$199.99",
		state: "MA",
		retail: "Liquor Junction",
		image: "",
		label: "e-m14-47-l.jpg"
	},

	{
		id: 243,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-M14-54",
		age: "14yrs 5mos",
		proof: "135",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "May/2008",
		bottled: "Dec/2022",
		price: "$199.99",
		state: "MA",
		retail: "Liquor Junction",
		image: "",
		label: "e-m14-54-l.jpg"
	},

	{
		id: 244,
		name: "Commonwealth of Massachusetts",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-M14-55",
		age: "14yrs 5mos",
		proof: "135.52",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "May/2023",
		bottled: "Dec/2022",
		price: "$184.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: "",
		label: ""
	},

	{
		id: 245,
		name: "Gordon's",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-M9-28",
		age: "9yrs",
		proof: "131.9",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "Apr/2014",
		bottled: "Dec/2022",
		price: "$114.99",
		state: "MA",
		retail: "Gordon's Wine",
		image: "",
		label: ""
	},

	{
		id: 246,
		name: "Commonwealth of Massachusetts",
		type: "Malt",
		series: "Exceptional",
		barrel: "E-M9-35",
		age: "9yrs 6mos",
		proof: "132.04",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "Apr/2013",
		bottled: "Feb/2023",
		price: "$109.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: "",
		label: ""
	},

	{
		id: 247,
		name: "Joe C with No Us Without You",
		type: "Malt",
		series: "Exceptional",
		barrel: "EM-8-101",
		age: "8yrs 6mos",
		proof: "131.26",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "Apr/2014",
		bottled: "Nov/2022",
		price: "$99.50",
		state: "CA",
		retail: "Everson Royce",
		image: "em-8-101.jpg",
		label: "em-8-101-l.jpg"
	},

	{
		id: 248,
		name: "The Vineyard",
		type: "Malt",
		series: "Exceptional",
		barrel: "M-45",
		age: "",
		proof: "",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NJ",
		retail: "The Vineyard Wines and Liquor",
		image: "",
		label: ""
	},

	{
		id: 249,
		name: "Justin's House of Bourbon",
		type: "Malt",
		series: "Exceptional",
		barrel: "",
		age: "14yrs",
		proof: "133.8",
		finish: "",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Justin's House of Bourbon",
		image: "",
		label: ""
	},

	{
		id: 250,
		name: "Unknown",
		type: "Malt",
		series: "Exceptional",
		barrel: "",
		age: "",
		proof: "",
		finish: "Cognac",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "unknown-exceptional-cognac-l.jpg"
	},

	{
		id: 251,
		name: "Unknown",
		type: "Malt",
		series: "Exceptional",
		barrel: "",
		age: "",
		proof: "",
		finish: "Barbados Rum",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "unknown-exceptional-barbados-rum-l.jpg"
	},

	{
		id: 252,
		name: "Unknown",
		type: "Malt",
		series: "Exceptional",
		barrel: "",
		age: "",
		proof: "",
		finish: "Madeira",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "unknown-exceptional-madeira-l.jpg"
	},

	{
		id: 253,
		name: "Unknown",
		type: "Malt",
		series: "Exceptional",
		barrel: "",
		age: "",
		proof: "",
		finish: "Armagnac",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: ""
	},

	{
		id: 254,
		name: "Rite Selection",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "MAD-B-09",
		age: "6yrs 7mos",
		proof: "114.5",
		finish: "Madeira",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "$84.99",
		state: "NJ",
		retail: "Buy Rite",
		image: "",
		label: ""
	},

	{
		id: 255,
		name: "Joe Canal's / Benash Liquors",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "OLS-B-03",
		age: "6yrs 5mos",
		proof: "112.06",
		finish: "Oloroso",
		mashbill: "65/35",
		source: "",
		distilled: "",
		bottled: "",
		price: "$89.99",
		state: "NJ",
		retail: "Joe Canal's & Benash Liquors",
		image: "",
		label: ""
	},

	{
		id: 256,
		name: "Rite Selection",
		type: "Rye",		
		series: "Single Barrel",
		barrel: "KRY-549",
		age: "6yrs 6mos",
		proof: "121.18",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$84.99",
		state: "NJ",
		retail: "Buy Rite",
		image: "",
		label: ""
	},

	{
		id: 257,
		name: "Joe Canal's / Benash Liquors",
		type: "Rye",
		series: "Single Barrel",
		barrel: "KRY-518",
		age: "6yrs 7mos",
		proof: "115.18",
		finish: "",
		mashbill: "95/5",
		source: "Bardstown",
		distilled: "",
		bottled: "",
		price: "$89.99",
		state: "NJ",
		retail: "Joe Canal's & Benash Liquors",
		image: "",
		label: ""
	},

	{
		id: 258,
		name: "Warped Cigars",
		type: "Bourbon",
		series: "Single Barrel",
		barrel: "RIO-251A",
		age: "6yrs 7mos",
		proof: "113.2",
		finish: "",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "warped-l.jpg"
	},

	{
		id: 259,
		name: "Batch Tucson",
		type: "Rye",
		series: "Single Barrel",
		barrel: "AMB-R-01",
		age: "5yrs 11mos",
		proof: "114.48",
		finish: "Amburana",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: "",
		label: "amb-r-01-l.jpg"
	}
];

// Set item count
var itemCount = 0;

// Check for id parameter in URL
var urlParams = new URLSearchParams(window.location.search);
var release = urlParams.get('id');


// Details page
if (release) {
    // Filter items based on release id
    var filteredItems = items.filter(function(item) {
        return item.id == release;
    });

    // Display filtered items
    var itemList = document.getElementById("detail-list");
    itemList.innerHTML = "";
	
    for (var i = 0; i < filteredItems.length; i++) {
        var item = filteredItems[i];
		console.log(items);
        var itemDiv = document.createElement("div");
        itemDiv.classList.add("detail-container");
        itemDiv.innerHTML = `
                <div>
                    ${item.image ? `<img src="images/${item.image}" height="300">` : ""}
                </div>
                <div>
					<h2>${item.name}</h2>
                    Barrel: ${item.barrel}<br>
                    Type: ${item.type}<br>
                    Finish: ${item.finish}<br>
					Age: ${item.age}<br>
					Proof: ${item.proof}<br>
					Mashbill: ${item.mashbill}<br>
					Source: ${item.source}<br>
					Distilled on: ${item.distilled}<br>
					Bottled on: ${item.bottled}<br>
					Retail price: ${item.price}<br>
					Release state: ${item.state}<br>
					Retail partner: ${item.retail}
                </div>
        `;
        itemList.appendChild(itemDiv);
    }
} else {
var itemList = document.getElementById("item-list");

items.sort((a, b) => a.name.localeCompare(b.name));
itemCount = items.length;



for (var i = 0; i < items.length; i++) {
	var item = items[i];
	var itemDiv = document.createElement("div");
	itemDiv.classList.add("card");
	itemDiv.innerHTML = `
	<div class="card-content">
	<div class="card-image">
	${item.label ? `<img src="images/${item.label}">` : `<div class="card-placeholder"></div>`}
    </div>
	<div class="card-text">
	<div class="card-header header">${item.name}</div>
    ${item.barrel}<br>
	${item.type}
	<div class="finish-tag ${item.finish.toLowerCase().replace(/\s+/g, "-")}">${item.finish}</div>
	</div>
	</div>
	</div>
	`;
	itemList.appendChild(itemDiv);

	// Add click event listener to the card element
	itemDiv.addEventListener("click", (function(itemCopy) {
		return function() {
			viewItemDetails(itemCopy.id);
		}
	})(item));
	
	var countDisplay = document.getElementById("count-display");
	countDisplay.innerHTML = "Release count: " + itemCount;

	// Filter drawer
	const openButton = document.getElementById('open-button');
	const closeButton = document.getElementById('close-button');
	const filterDrawer = document.querySelector('.filterDrawer');
	const overlay = document.querySelector('.overlay');

	openButton.addEventListener('click', () => {
		filterDrawer.classList.add('open');
		overlay.classList.add('open');
	});

	closeButton.addEventListener('click', () => {
		filterDrawer.classList.remove('open');
		overlay.classList.remove('open');
	});

	overlay.addEventListener('click', () => {
		filterDrawer.classList.remove('open');
		overlay.classList.remove('open');
	});

}

function filterItems() {
	var finishFilter = document.getElementById("finish-filter").value;
  
	if (finishFilter === "") {
	  // Show all items if no filters are selected
	  showAllItems();
	} else {
	  // Filter items based on selected finish
	  var filteredItems = items.filter(function (item) {
		return item.finish.toLowerCase().indexOf(finishFilter.toLowerCase()) !== -1;
	  });
	  updateItemList(filteredItems);
	}
}

function filterItemsByType(type) {
	var filteredItems;
	if (type === '') {
	  filteredItems = items;
	} else {
	  filteredItems = items.filter(function(item) {
		return item.type === type;
	  });
	}
	updateItemList(filteredItems);
}


function showAllItems() {
	updateItemList(items);
}

function updateItemList(updatedItems) {
	var itemList = document.getElementById("item-list");
	itemList.innerHTML = "";
	itemCount = updatedItems.length;
	var count = updatedItems.length;

	for (var i = 0; i < updatedItems.length; i++) {
		var item = updatedItems[i];
		var itemDiv = document.createElement("div");
		itemDiv.classList.add("card");
		itemDiv.innerHTML = `
			<div class="card-content">
			<div class="card-image">
        		${item.label ? `<img src="images/${item.label}" width="100" height="100">` : ""}
    		</div>
			<div class="card-text">
				<div class="card-header header">${item.name}</div>
    			${item.barrel}<br>
				${item.type}
				${item.finish ? `<div class="finish-tag ${item.finish.toLowerCase().replace(/\s+/g, "-")}">${item.finish}</div>` : ""}
			</div>
			</div>
			</div>
			`;
		itemList.appendChild(itemDiv);

		// Add click event listener to the card element
		itemDiv.addEventListener("click", (function (itemCopy) {
			return function () {
				viewItemDetails(itemCopy.id);
		}
	})(item));
	}
	var countDisplay = document.getElementById("count-display");
	countDisplay.innerHTML = "Release count: " + itemCount;

	// Filter drawer
	const openButton = document.getElementById('open-button');
	const closeButton = document.getElementById('close-button');
	const filterDrawer = document.querySelector('.filterDrawer');
	const overlay = document.querySelector('.overlay');

	openButton.addEventListener('click', () => {
		filterDrawer.classList.add('open');
		overlay.classList.add('open');
	});

	closeButton.addEventListener('click', () => {
		filterDrawer.classList.remove('open');
		overlay.classList.remove('open');
	});

	overlay.addEventListener('click', () => {
		filterDrawer.classList.remove('open');
		overlay.classList.remove('open');
	});

}


// GENERATE LINK TO DETAILS PAGE
function viewItemDetails(itemId) {
	window.location.href = "details.html?id=" + itemId;
}
}