var items = [
	{
		id: 1,
		name: "@WhiskyVegas",
		type: "Bourbon",
		barrel: "OLS-B-1",
		age: "6yrs 1mo",
		proof: "119.34",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 2,
		name: "Alec Bradley",
		type: "Bourbon",
		barrel: "RIO-289",
		age: "6yrs 4mos",
		proof: "116.62",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 3,
		name: "Allocated Liquor",
		type: "Bourbon",
		barrel: "I21-06",
		age: "4yrs 4mos",
		proof: "116.6",
		finish: "None",
		mashbill: "",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.95",
		state: "CA",
		retail: "Top Bourbon",
		image: ""
		},
		
		{
		id: 4,
		name: "Bar Keeper",
		type: "Bourbon",
		barrel: "IRT-42-A",
		age: "5yrs",
		proof: "120.76",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 5,
		name: "Barrels & Brews",
		type: "Bourbon",
		barrel: "IRT-06",
		age: "5yrs 6mos",
		proof: "117.98",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 6,
		name: "Big Corks Germantown",
		type: "Bourbon",
		barrel: "IRT-26",
		age: "5yrs 6mos",
		proof: "117.42",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Corks Wine & Spirits",
		image: ""
		},
		
		{
		id: 7,
		name: "Bourbon Buddy",
		type: "Bourbon",
		barrel: "RIO-248",
		age: "6yrs",
		proof: "113.7",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 8,
		name: "Bourbon Enthusiast",
		type: "Bourbon",
		barrel: "RIO-223",
		age: "5yrs 9mos",
		proof: "115.8",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "Royal Batch",
		image: ""
		},
		
		{
		id: 9,
		name: "Bourbon Junkies",
		type: "Bourbon",
		barrel: "CC-2",
		age: "6yrs 2mos",
		proof: "117.4",
		finish: "Cognac",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 10,
		name: "Bourbon Junkies",
		type: "Bourbon",
		barrel: "RIO-209",
		age: "6yrs 1mo",
		proof: "117.86",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 11,
		name: "Bourbons Bistro",
		type: "Bourbon",
		barrel: "IRT-55",
		age: "5yrs 4mos",
		proof: "122.64",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 12,
		name: "Burlington Wine & Spirits",
		type: "Bourbon",
		barrel: "RIO-227",
		age: "6yrs 7mos",
		proof: "115.58",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "12/22",
		price: "$79.99",
		state: "MA",
		retail: "Burlington Wine & Spirits",
		image: ""
		},
		
		{
		id: 13,
		name: "Buster's Liquor & Wine",
		type: "Bourbon",
		barrel: "IRT-15",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$71.99",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: ""
		},
		
		{
		id: 14,
		name: "Buster's Liquor & Wine",
		type: "Bourbon",
		barrel: "RIO-228",
		age: "6yrs 6mos",
		proof: "114.1",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$81.99",
		state: "TN",
		retail: "Buster's Liquor & Wine",
		image: ""
		},
		
		{
		id: 15,
		name: "Casa Fuente",
		type: "Bourbon",
		barrel: "OLS-B-2",
		age: "6yrs 5mos",
		proof: "110.78",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 16,
		name: "Cask",
		type: "Bourbon",
		barrel: "IRT-33",
		age: "5yrs 11mos",
		proof: "117.7",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 17,
		name: "Chasing Bourbon",
		type: "Bourbon",
		barrel: "RIO-287",
		age: "6yrs 6mos",
		proof: "115.64",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 18,
		name: "Chestnut Club",
		type: "Bourbon",
		barrel: "IRT-44",
		age: "5yrs",
		proof: "121.84",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "12/13/16",
		bottled: "11/12/21",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 19,
		name: "Chinglish",
		type: "Bourbon",
		barrel: "RIO-296",
		age: "5yrs 7mos",
		proof: "93",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 20,
		name: "Chip's Liquor",
		type: "Bourbon",
		barrel: "RIO-222-C",
		age: "6yrs 1mo",
		proof: "115.6",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$74.99",
		state: "CA",
		retail: "Chip's Liquor",
		image: ""
		},
		
		{
		id: 21,
		name: "Corona Cigars",
		type: "Bourbon",
		barrel: "RIO-224",
		age: "6yrs 4mos",
		proof: "116.26",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "FL",
		retail: "",
		image: ""
		},
		
		{
		id: 22,
		name: "Cosmopolitan",
		type: "Bourbon",
		barrel: "MAD-B-05",
		age: "5yrs 5mos",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "4/2022",
		price: "",
		state: "NV",
		retail: "NFS",
		image: ""
		},
		
		{
		id: 23,
		name: "Cosmopolitan",
		type: "Bourbon",
		barrel: "RIO-269",
		age: "6yrs 7mos",
		proof: "112.64",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "NFS",
		image: ""
		},
		
		{
		id: 24,
		name: "Curiada",
		type: "Bourbon",
		barrel: "IRT-02",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CT",
		retail: "Curiada",
		image: ""
		},
		
		{
		id: 25,
		name: "Del Mesa Liquor",
		type: "Bourbon",
		barrel: "RIO-222-A",
		age: "6yrs 1mo",
		proof: "115.6",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$79.99",
		state: "CA",
		retail: "Del Mesa Liquor",
		image: ""
		},
		
		{
		id: 26,
		name: "Dion's",
		type: "Bourbon",
		barrel: "RIO-238",
		age: "6yrs 7mos",
		proof: "113.42",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "MA",
		retail: "Dion's ",
		image: ""
		},
		
		{
		id: 27,
		name: "Dion's",
		type: "Bourbon",
		barrel: "RIO-240",
		age: "6yrs 7mos",
		proof: "114.14",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "MA",
		retail: "Dion's",
		image: ""
		},
		
		{
		id: 28,
		name: "Eataly at Park MGM",
		type: "Bourbon",
		barrel: "RIO-242",
		age: "5yrs 10mos",
		proof: "94",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$120.00",
		state: "NV",
		retail: "Eataly",
		image: ""
		},
		
		{
		id: 29,
		name: "El Cerrito Liquor",
		type: "Bourbon",
		barrel: "IRT-25",
		age: "5yrs 6mos",
		proof: "117.22",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "5/22",
		price: "$75.00",
		state: "CA",
		retail: "El Cerrito",
		image: ""
		},
		
		{
		id: 30,
		name: "Elixir",
		type: "Bourbon",
		barrel: "IRT-51",
		age: "5yrs 10mos",
		proof: "120.78",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 31,
		name: "Ettan",
		type: "Bourbon",
		barrel: "RIO-205",
		age: "5yrs 9mos",
		proof: "90",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 32,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "RIO-243",
		age: "6yrs 2mos",
		proof: "104.58",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 33,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "RIO-255",
		age: "6yrs 2mos",
		proof: "118.02",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 34,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-03",
		age: "4yrs 7mos",
		proof: "114.94",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 35,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-07",
		age: "",
		proof: "116.44",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 36,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-09",
		age: "",
		proof: "116.2",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 37,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-11",
		age: "",
		proof: "118.24",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 38,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-14",
		age: "4yrs 9mos",
		proof: "116.86",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 39,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-15",
		age: "",
		proof: "117.86",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 40,
		name: "Eureka!",
		type: "Bourbon",
		barrel: "I21-20",
		age: "4yrs 9mos",
		proof: "115.24",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Eureka",
		image: ""
		},
		
		{
		id: 41,
		name: "Fernside",
		type: "Bourbon",
		barrel: "RIO-239",
		age: "5yrs 10mos",
		proof: "113.92",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 42,
		name: "Founder's Choice",
		type: "Bourbon",
		barrel: "IRT-07",
		age: "5yrs 7mos",
		proof: "118.48",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "NY",
		retail: "Mash & Grape",
		image: ""
		},
		
		{
		id: 43,
		name: "Founder's Choice",
		type: "Bourbon",
		barrel: "IRT-20",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "NY",
		retail: "Mash & Grape",
		image: ""
		},
		
		{
		id: 44,
		name: "Founder's Choice",
		type: "Bourbon",
		barrel: "RIO-273",
		age: "5yrs 8mos",
		proof: "116.36",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NY",
		retail: "",
		image: ""
		},
		
		{
		id: 45,
		name: "George Awad and the Neat Freaks",
		type: "Bourbon",
		barrel: "BAL-B-02",
		age: "5yrs 2mos",
		proof: "114.06",
		finish: "Balsamo",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "FL",
		retail: "Sunshine Liquor",
		image: ""
		},
		
		{
		id: 46,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		barrel: "RIO-213",
		age: "6yrs",
		proof: "116.96",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 47,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		barrel: "RIO-214",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 48,
		name: "Germantown Village Wine & Liquor",
		type: "Bourbon",
		barrel: "RIO-260",
		age: "6yrs 6mos",
		proof: "112.24",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 49,
		name: "Good Lion",
		type: "Bourbon",
		barrel: "IRT-05",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 50,
		name: "Gordon's Est 1934 @TheWhiskyGuys",
		type: "Bourbon",
		barrel: "RIO-270",
		age: "6yrs 7mos",
		proof: "117.14",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "12/22",
		price: "$74.99",
		state: "MA",
		retail: "Gordon's Wine",
		image: ""
		},
		
		{
		id: 51,
		name: "Hatchet Hall",
		type: "Bourbon",
		barrel: "IRT-46",
		age: "",
		proof: "107.2",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 52,
		name: "Helix Liquor",
		type: "Bourbon",
		barrel: "RIO-222B",
		age: "6yrs 1mos",
		proof: "115.6",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$79.99",
		state: "CA",
		retail: "Bottle Broz",
		image: ""
		},
		
		{
		id: 53,
		name: "Heritage Selections",
		type: "Bourbon",
		barrel: "RIO-229",
		age: "5yrs 8mos",
		proof: "114.92",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 54,
		name: "Heritage Selections",
		type: "Bourbon",
		barrel: "I21-08",
		age: "4yrs 5mos",
		proof: "116.3",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 55,
		name: "Hi-Time Wine Cellars",
		type: "Bourbon",
		barrel: "RIO-295",
		age: "5yrs 9mos",
		proof: "117.12",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Hi-Time Wine Cellars",
		image: ""
		},
		
		{
		id: 56,
		name: "Hotel Covington",
		type: "Bourbon",
		barrel: "RIO-265",
		age: "5yrs 8mos",
		proof: "117.96",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 57,
		name: "Jarred Dooley",
		type: "Bourbon",
		barrel: "IRT-40",
		age: "5yrs",
		proof: "119.22",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/12/16",
		bottled: "11/12/21",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 58,
		name: "Joe C",
		type: "Bourbon",
		barrel: "IRT-27",
		age: "5yrs",
		proof: "116.66",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16/16",
		bottled: "11/28/21",
		price: "",
		state: "CA",
		retail: "Everson Royce",
		image: ""
		},
		
		{
		id: 59,
		name: "Joe C",
		type: "Bourbon",
		barrel: "JR-1 / KHT-02",
		age: "4yrs 11mos",
		proof: "118.48",
		finish: "Jamaican Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "4/22",
		price: "$103.00",
		state: "CA",
		retail: "Everson Royce",
		image: ""
		},
		
		{
		id: 60,
		name: "Joe C with No Us Without You",
		type: "Bourbon",
		barrel: "RIO-213-A",
		age: "6yrs",
		proof: "113.72",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "6/22",
		price: "$92.00",
		state: "CA",
		retail: "Everson Royce",
		image: ""
		},
		
		{
		id: 61,
		name: "Justin's House of Bourbon",
		type: "Bourbon",
		barrel: "RIO-256",
		age: "6yrs",
		proof: "118.34",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Justin's House of Bourbon",
		image: ""
		},
		
		{
		id: 62,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		barrel: "IRT-21",
		age: "5yrs",
		proof: "119.68",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: ""
		},
		
		{
		id: 63,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		barrel: "IRT-24",
		age: "5yrs",
		proof: "119.68",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: ""
		},
		
		{
		id: 64,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		barrel: "RIO-234",
		age: "6yrs",
		proof: "115.44",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: ""
		},
		
		{
		id: 65,
		name: "K&L Wine Merchants",
		type: "Bourbon",
		barrel: "RIO-254",
		age: "6yrs",
		proof: "112.86",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: ""
		},
		
		{
		id: 66,
		name: "Khoury's",
		type: "Bourbon",
		barrel: "WP-B-05",
		age: "6yrs 6mos",
		proof: "104.42",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "11/22",
		price: "",
		state: "NV",
		retail: "Khoury's",
		image: ""
		},
		
		{
		id: 67,
		name: "Khoury's Fine Wine",
		type: "Bourbon",
		barrel: "RIO-261",
		age: "6yrs",
		proof: "114.04",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Khoury's",
		image: ""
		},
		
		{
		id: 68,
		name: "Lake District Wine & Liquor",
		type: "Bourbon",
		barrel: "IRT-10",
		age: "5yrs 6mos",
		proof: "120.16",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 69,
		name: "Laundry Room",
		type: "Bourbon",
		barrel: "I21-16",
		age: "4yrs 6mos",
		proof: "96",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "NFS",
		image: ""
		},
		
		{
		id: 70,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		barrel: "IRT-18",
		age: "5yrs 4mos",
		proof: "118.8",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: ""
		},
		
		{
		id: 71,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		barrel: "OLS-B-05",
		age: "5yrs 11mos",
		proof: "112.74",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: ""
		},
		
		{
		id: 72,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		barrel: "RIO-232",
		age: "6yrs 5mos",
		proof: "112.84",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: ""
		},
		
		{
		id: 73,
		name: "Lee's Discount Liquor",
		type: "Bourbon",
		barrel: "RIO-244",
		age: "5yrs 10mos",
		proof: "114.72",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "Lee's Discount Liquor",
		image: ""
		},
		
		{
		id: 74,
		name: "Life of Luxe",
		type: "Bourbon",
		barrel: "RIO-262",
		age: "6yrs",
		proof: "118.34",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 75,
		name: "Liquor Barn",
		type: "Bourbon",
		barrel: "IRT-38",
		age: "5yrs 1mo",
		proof: "118.26",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "12/16",
		bottled: "1/22",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: ""
		},
		
		{
		id: 76,
		name: "Liquor Barn",
		type: "Bourbon",
		barrel: "RIO-300",
		age: "5yrs 7mos",
		proof: "116.3",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: ""
		},
		
		{
		id: 77,
		name: "Liquor Barn",
		type: "Bourbon",
		barrel: "I21-12",
		age: "4yrs 6mos",
		proof: "116.76",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "Liquor Barn",
		image: ""
		},
		
		{
		id: 78,
		name: "Liquor Junction & Mass Bourbon Alliance",
		type: "Bourbon",
		barrel: "OLS-13-04",
		age: "6yrs 7mos",
		proof: "110.1",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "12/22",
		price: "",
		state: "MA",
		retail: "Liquor Junction",
		image: ""
		},
		
		{
		id: 79,
		name: "LiquorLineup.com",
		type: "Bourbon",
		barrel: "RIO-219",
		age: "5yrs 7mos",
		proof: "117.74",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "NV",
		retail: "LiquorLineup.com",
		image: ""
		},
		
		{
		id: 80,
		name: "Littlebear Bottleshop",
		type: "Bourbon",
		barrel: "IRT-42-B",
		age: "5yrs",
		proof: "120.76",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 81,
		name: "Littlebear Bottleshop",
		type: "Bourbon",
		barrel: "OLS-B-06",
		age: "5yrs 6mos",
		proof: "110.78",
		finish: "Oloroso",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 82,
		name: "Local Feed",
		type: "Bourbon",
		barrel: "RIO-286-B",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 83,
		name: "Lotus of Siam",
		type: "Bourbon",
		barrel: "RIO-204",
		age: "6yrs 1mo",
		proof: "95",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 84,
		name: "Lotus of Siam",
		type: "Bourbon",
		barrel: "RIO-226",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 85,
		name: "Major League Bourbon Clubhouse",
		type: "Bourbon",
		barrel: "",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
		},
		
		{
		id: 86,
		name: "Majority Rule",
		type: "Bourbon",
		barrel: "IRT-53",
		age: "5yrs 7mos",
		proof: "111.14",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 87,
		name: "Mash & Journey Whiskey Club",
		type: "Bourbon",
		barrel: "RIO-290",
		age: "6yrs",
		proof: "113.54",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$82.99",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 88,
		name: "MGM Resorts",
		type: "Bourbon",
		barrel: "RIO-251",
		age: "6yrs 5mos",
		proof: "95",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 89,
		name: "Michael Mina",
		type: "Bourbon",
		barrel: "RIO-201",
		age: "5yrs 9mos",
		proof: "115.84",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 90,
		name: "Michael Mina",
		type: "Bourbon",
		barrel: "RIO-220",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 91,
		name: "Michael Mina",
		type: "Bourbon",
		barrel: "RIO-283",
		age: "6yrs",
		proof: "104.24",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 92,
		name: "Michael P. Trow & Gia St. George Terry",
		type: "Bourbon",
		barrel: "RIO-211",
		age: "6yrs 5mos",
		proof: "95.4",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/2016",
		bottled: "10/2022",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 93,
		name: "Mission Wine & Spirits",
		type: "Bourbon",
		barrel: "IRT-30",
		age: "5yrs",
		proof: "119.58",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 94,
		name: "Mission Wine & Spirits",
		type: "Bourbon",
		barrel: "IRT-59",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 95,
		name: "Mister O's",
		type: "Bourbon",
		barrel: "IRT-19-B",
		age: "5yrs 8mos",
		proof: "118.28",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 96,
		name: "Mixing Glass",
		type: "Bourbon",
		barrel: "IRT-12-B",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 97,
		name: "Mixing Glass",
		type: "Bourbon",
		barrel: "I21-13-A",
		age: "4yrs 4mos",
		proof: "117.6",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 98,
		name: "Moye O'Brien Bourbon Crew",
		type: "Bourbon",
		barrel: "RIO-218",
		age: "6yrs 4mos",
		proof: "114.78",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
		},
		
		{
		id: 99,
		name: "Mr Whiskers",
		type: "Bourbon",
		barrel: "IRT-03",
		age: "5yrs 11mos",
		proof: "119.74",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Mr Whiskers Wines & Liquors",
		image: ""
		},
		
		{
		id: 100,
		name: "Mr Whiskers",
		type: "Bourbon",
		barrel: "RIO-288",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "Mr Whiskers Wines & Liquors",
		image: ""
		},
		
		{
		id: 101,
		name: "Mythical",
		type: "Bourbon",
		barrel: "MAD-4",
		age: "5yrs",
		proof: "117.23",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "",
		retail: "",
		image: ""
		},
		
		{
		id: 102,
		name: "Nashville Daily",
		type: "Bourbon",
		barrel: "IRT-41",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 103,
		name: "OBC Kitchen",
		type: "Bourbon",
		barrel: "121-13-B",
		age: "4yrs 4mos",
		proof: "117.6",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "7/17",
		bottled: "11/21",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 104,
		name: "Old Man Bar",
		type: "Bourbon",
		barrel: "IRT-18",
		age: "4yrs 4mos",
		proof: "116.14",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 105,
		name: "Old Man Bar",
		type: "Bourbon",
		barrel: "IRT-46",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 106,
		name: "Old Man Bar",
		type: "Bourbon",
		barrel: "I21-18",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 107,
		name: "On The Thirty",
		type: "Bourbon",
		barrel: "IRT-19-A",
		age: "5yrs 2mos",
		proof: "118.28",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 108,
		name: "Pablo Moix",
		type: "Bourbon",
		barrel: "",
		age: "14yrs",
		proof: "143.8",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$599.99",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 109,
		name: "Pacifica Hotels",
		type: "Bourbon",
		barrel: "I21-01",
		age: "",
		proof: "90",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 110,
		name: "Party Source",
		type: "Bourbon",
		barrel: "RIO-259",
		age: "5yrs 9mos",
		proof: "117.12",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 111,
		name: "Prime Barrel",
		type: "Bourbon",
		barrel: "RIO-235",
		age: "6yrs 6mos",
		proof: "113.18",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
		},
		
		{
		id: 112,
		name: "Raised by Wolves",
		type: "Bourbon",
		barrel: "IRT-34",
		age: "5yrs 1 mo",
		proof: "116.26",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "Bar Cart",
		image: ""
		},
		
		{
		id: 113,
		name: "Rapid Liquors",
		type: "Bourbon",
		barrel: "RIO-236",
		age: "6yrs 7mos",
		proof: "114.12",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$68.99",
		state: "MA",
		retail: "Rapid Liquors",
		image: ""
		},
		
		{
		id: 114,
		name: "Rare Bird 101",
		type: "Bourbon",
		barrel: "RIO-241",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 115,
		name: "Raymond 1886",
		type: "Bourbon",
		barrel: "RIO-297",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 116,
		name: "Red Dog",
		type: "Bourbon",
		barrel: "IRT-17",
		age: "5yrs 6mos",
		proof: "117.66",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "TN",
		retail: "Red Dog",
		image: ""
		},
		
		{
		id: 117,
		name: "Red Dog",
		type: "Bourbon",
		barrel: "JR-B-02",
		age: "4yrs 10mos",
		proof: "118.48",
		finish: "Jamaican Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "TN",
		retail: "Red Dog",
		image: ""
		},
		
		{
		id: 118,
		name: "Red Dog",
		type: "Bourbon",
		barrel: "WP-B-04",
		age: "5yrs",
		proof: "110.82",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$109.99",
		state: "TN",
		retail: "Red Dog",
		image: ""
		},
		
		{
		id: 119,
		name: "Redbird",
		type: "Bourbon",
		barrel: "RIO-278",
		age: "6yrs",
		proof: "114.8",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 120,
		name: "Republique",
		type: "Bourbon",
		barrel: "RIO-264",
		age: "5yrs 3mos",
		proof: "113.68",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "May 2016",
		bottled: "Jan 2022",
		price: "",
		state: "CA",
		retail: "Republique",
		image: ""
		},
		
		{
		id: 121,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		barrel: "IRT-25-2",
		age: "5yrs 4mos",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$114.99",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 122,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		barrel: "IRT-36A",
		age: "6yrs",
		proof: "115.12",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 123,
		name: "Revival Vintage Bottle Shop",
		type: "Bourbon",
		barrel: "RIO-286-A",
		age: "6yrs",
		proof: "115.12",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
		},
		
		{
		id: 124,
		name: "Sahara Las Vegas",
		type: "Bourbon",
		barrel: "IRT-23",
		age: "5yrs",
		proof: "89.5",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 125,
		name: "Sahara Las Vegas",
		type: "Bourbon",
		barrel: "MAD-1",
		age: "5yrs",
		proof: "104",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 126,
		name: "Sand Dollar",
		type: "Bourbon",
		barrel: "RIO-298",
		age: "6yrs 5mos",
		proof: "113.02",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 127,
		name: "Santee Market & Liquor / BPWC",
		type: "Bourbon",
		barrel: "IRT-13",
		age: "6yrs",
		proof: "117.72",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "11/22",
		price: "$79.99",
		state: "CA",
		retail: "F&D Wine and Spirits",
		image: ""
		},
		
		{
		id: 128,
		name: "Scopa Italian Roots",
		type: "Bourbon",
		barrel: "IRT-22",
		age: "5yrs",
		proof: "119.18",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 129,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "IRT-35",
		age: "5yrs",
		proof: "117.32",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 130,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "IRT-60",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 131,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "MAD-B-1",
		age: "5yrs",
		proof: "112.68",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 132,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "WP-1",
		age: "6yrs 7mos",
		proof: "113.48",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 133,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "RIO-202",
		age: "6yrs",
		proof: "115.52",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 134,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "RIO-252",
		age: "6yrs",
		proof: "113.62",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "5/22",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 135,
		name: "Seelbach's",
		type: "Bourbon",
		barrel: "RIO-267",
		age: "6yrs",
		proof: "114.78",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$89.00",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 136,
		name: "Seelbach's & Bourbon Enthusiast",
		type: "Bourbon",
		barrel: "WP-B-2",
		age: "5yrs",
		proof: "109.26",
		finish: "White Port",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "6/22",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 137,
		name: "Sinkers Wine & Spirits",
		type: "Bourbon",
		barrel: "RIO-282",
		age: "6yrs 2mos",
		proof: "118.2",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
		},
		
		{
		id: 138,
		name: "Southern Arizona Whiskey Society",
		type: "Bourbon",
		barrel: "WP-B-03",
		age: "5yrs 6mos",
		proof: "111.1",
		finish: "White Port",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "AZ",
		retail: "Batch",
		image: ""
		},
		
		{
		id: 139,
		name: "Southern Whiskey Society",
		type: "Bourbon",
		barrel: "IRT-54",
		age: "5yrs 7mos",
		proof: "102.6",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$69.99",
		state: "TN",
		retail: "Red Dog",
		image: ""
		},
		
		{
		id: 140,
		name: "Spiegelworld",
		type: "Bourbon",
		barrel: "IRT-31",
		age: "5yrs 7mos",
		proof: "119.9",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "6/22",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 141,
		name: "Spiegelworld",
		type: "Bourbon",
		barrel: "IRT-31",
		age: "5yrs 7mos",
		proof: "95",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "11/16",
		bottled: "6/22",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 142,
		name: "Spiegelworld",
		type: "Bourbon",
		barrel: "KHT-22",
		age: "5yrs",
		proof: "59.11",
		finish: "None",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "$250.00",
		state: "NV",
		retail: "",
		image: ""
		},
		
		{
		id: 143,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		barrel: "IRT-29",
		age: "5yrs 6mos",
		proof: "116.88",
		finish: "PX Sherry",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$99.99",
		state: "DC",
		retail: "Seelbach's",
		image: ""
		},
		
		{
		id: 144,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		barrel: "RIO-215",
		age: "5yrs 8mos",
		proof: "112.52",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 145,
		name: "T8ke for r/Bourbon",
		type: "Bourbon",
		barrel: "RIO-221",
		age: "5yrs 8mos",
		proof: "115.52",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "5/16",
		bottled: "1/22",
		price: "",
		state: "DC",
		retail: "",
		image: ""
		},
		
		{
		id: 146,
		name: "Thunderbolt",
		type: "Bourbon",
		barrel: "IRT-11",
		age: "5yrs",
		proof: "90",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
		},
		
		{
		id: 147,
		name: "Top's Liquor",
		type: "Bourbon",
		barrel: "MAD-B-58",
		age: "5yrs",
		proof: "112.34",
		finish: "Madeira",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Top's Liquor",
		image: ""
		},
		
		{
		id: 148,
		name: "Top's Liquor",
		type: "Bourbon",
		barrel: "RIO-206",
		age: "6yrs 5mos",
		proof: "113.02",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Top's Liquor",
		image: ""
		},
		
		{
		id: 149,
		name: "Total Wine & More",
		type: "Bourbon",
		barrel: "FSR-B-02",
		age: "6yrs 7mos",
		proof: "110.34",
		finish: "Foursquare Rum",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	},
		
	{
		id: 150,
		name: "Trevor's Liquors",
		type: "Bourbon",
		barrel: "RIO-212",
		age: "6yrs 1mos",
		proof: "115.52",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "AZ",
		retail: "Trevor's Liquors",
		image: ""
	},
		
	{
		id: 151,
		name: "Vintage Corks",
		type: "Bourbon",
		barrel: "IRT-09",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},
		
	{
		id: 152,
		name: "Vintage Corks",
		type: "Bourbon",
		barrel: "IRT-28",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},
		
	{
		id: 153,
		name: "Vintage Corks",
		type: "Bourbon",
		barrel: "RIO-287",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},
		
	{
		id: 154,
		name: "Westport Whiskey & Wine",
		type: "Bourbon",
		barrel: "RIO-249",
		age: "5yrs 7mos",
		proof: "114.18",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "KY",
		retail: "",
		image: ""
	},
		
	{
		id: 155,
		name: "Whiskey Locator",
		type: "Bourbon",
		barrel: "RIO-299",
		age: "6yrs",
		proof: "118.48",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "$79.99",
		state: "CA",
		retail: "K&L Wine Merchants",
		image: ""
	},
		
	{
		id: 156,
		name: "Wine Chap",
		type: "Bourbon",
		barrel: "IRT-32",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},
		
	{
		id: 157,
		name: "Wine Chap",
		type: "Bourbon",
		barrel: "RIO-207",
		age: "6yrs 5mos",
		proof: "114.48",
		finish: "None",
		mashbill: "75/21/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "TN",
		retail: "",
		image: ""
	},
		
	{
		id: 158,
		name: "Winston House",
		type: "Bourbon",
		barrel: "IRT-37",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},
		
	{
		id: 159,
		name: "Winston House",
		type: "Bourbon",
		barrel: "IRT-45",
		age: "",
		proof: "",
		finish: "None",
		mashbill: "60/36/4",
		source: "MGP",
		distilled: "",
		bottled: "",
		price: "",
		state: "CA",
		retail: "",
		image: ""
	},
		
	{
		id: 160,
		name: "",
		type: "Bourbon",
		barrel: "",
		age: "",
		proof: "",
		finish: "Eucalipto",
		mashbill: "",
		source: "",
		distilled: "",
		bottled: "",
		price: "",
		state: "",
		retail: "",
		image: ""
	}
];

var itemList = document.getElementById("item-list");

for (var i = 0; i < items.length; i++) {
	var item = items[i];
	var itemDiv = document.createElement("div");
	itemDiv.classList.add("card");
	itemDiv.innerHTML = `
		<h2>${item.name}</h2>
		<p>${item.barrel}<br>
		${item.type}<br>
		${item.finish}</p>
		<a href="javascript:viewItemDetails(${item.id})">View Details</a>
	`;
	//<button onclick="viewItemDetails(${item.id})">View Details</button>
	itemList.appendChild(itemDiv);
}

function viewItemDetails(itemId) {
	window.location.href = "details.html?id=" + itemId;
}

function filterItems() {
	var typeFilter = document.getElementById("type-filter").value;
	var finishFilter = document.getElementById("finish-filter").value;
  
	if (typeFilter === "" && finishFilter === "") {
	  // Show all items if no filters are selected
	  showAllItems();
	} else if (typeFilter !== "" && finishFilter === "") {
	  // Filter items based on selected type
	  var filteredItems = items.filter(function(item) {
		return item.type === typeFilter;
	  });
	  updateItemList(filteredItems);
	} else if (typeFilter === "" && finishFilter !== "") {
	  // Filter items based on selected finish
	  var filteredItems = items.filter(function(item) {
		return item.finish === finishFilter;
	  });
	  updateItemList(filteredItems);
	} else {
	  // Filter items based on both type and finish
	  var filteredItems = items.filter(function(item) {
		return item.type === typeFilter && item.finish === finishFilter;
	  });
	  updateItemList(filteredItems);
	}
  }
  

function showAllItems() {
	updateItemList(items);
}

function updateItemList(updatedItems) {
	var itemList = document.getElementById("item-list");
	itemList.innerHTML = "";

	for (var i = 0; i < updatedItems.length; i++) {
		var item = updatedItems[i];
		var itemDiv = document.createElement("div");
		itemDiv.classList.add("card");
		itemDiv.innerHTML = `
			<h2>${item.name}</h2>
			<p>${item.barrel}<br>
			${item.type}<br>
			${item.finish}</p>
			<a href="javascript:viewItemDetails(${item.id})">View Details</a>
		`;
		itemList.appendChild(itemDiv);
	}
}